<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:activities="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//activities" xmlns:callExpressions="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//calls/callExpressions" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:patternExpressions="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//patterns/patternExpressions" name="processing" nsURI="platform:/plugin/org.moflon.core.moca.processing/model/Processing.ecore" nsPrefix="org.moflon.core.moca.processing">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="basePackage" value="org.moflon.core.moca"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="CodeAdapter">
    <eOperations xsi:type="activities:MoflonEOperation" name="parse">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Folder"/>
      <eParameters name="dir" eType="//Directory"/>
    </eOperations>
    <eOperations xsi:type="activities:MoflonEOperation" name="unparse" eType="//Directory">
      <eParameters name="path">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eParameters>
      <eParameters name="folder">
        <eType xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Folder"/>
      </eParameters>
    </eOperations>
    <eOperations xsi:type="activities:MoflonEOperation" name="parseFile">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//File"/>
      <eParameters name="file" eType="//Directory"/>
      <eParameters name="parent">
        <eType xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Folder"/>
      </eParameters>
    </eOperations>
    <eOperations xsi:type="activities:MoflonEOperation" name="unparseFile">
      <eParameters name="eFile">
        <eType xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//File"/>
      </eParameters>
      <eParameters name="dir" eType="//Directory"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unparser" upperBound="-1" eType="//unparser/Unparser" containment="true" eOpposite="//unparser/Unparser/codeAdapter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="problems" upperBound="-1" eType="//Problem" containment="true" eOpposite="//Problem/codeAdapter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parser" upperBound="-1" eType="//parser/Parser" containment="true" eOpposite="//parser/Parser/codeAdapter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Directory" instanceClassName="java.io.File"/>
  <eClassifiers xsi:type="ecore:EDataType" name="File" instanceClassName="java.io.File"/>
  <eClassifiers xsi:type="ecore:EClass" name="Problem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="codeAdapter" lowerBound="1" eType="//CodeAdapter" eOpposite="//CodeAdapter/problems"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="characterPositionEnd" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="characterPositionStart" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="line" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" lowerBound="1" eType="//ProblemType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Reader" instanceClassName="java.io.Reader"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ProblemType">
    <eLiterals name="ERROR" literal="ERROR"/>
    <eLiterals name="WARNING" value="1" literal="WARNING"/>
    <eLiterals name="INFO" value="2" literal="INFO"/>
  </eClassifiers>
  <eSubpackages name="compare" nsURI="platform:/plugin/org.moflon.core.moca.processing/model/Processing.ecore#//compare" nsPrefix="compare">
    <eClassifiers xsi:type="ecore:EClass" name="Addition" eSuperTypes="//compare/MocaDiff"/>
    <eClassifiers xsi:type="ecore:EClass" name="Deletion" eSuperTypes="//compare/MocaDiff"/>
    <eClassifiers xsi:type="ecore:EClass" name="MocaCompare">
      <eOperations xsi:type="activities:MoflonEOperation" name="cacheRightFolder">
        <eParameters name="right">
          <eType xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Folder"/>
        </eParameters>
      </eOperations>
      <eOperations xsi:type="activities:MoflonEOperation" name="collectAddition">
        <eParameters name="element">
          <eType xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//TreeElement"/>
        </eParameters>
        <eParameters name="leftParent">
          <eType xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//TreeElement"/>
        </eParameters>
        <activity owningOperation="//compare/MocaCompare/collectAddition">
          <ownedActivityEdge source="//compare/MocaCompare/collectAddition/@activity/@ownedActivityNode.0" target="//compare/MocaCompare/collectAddition/@activity/@ownedActivityNode.1"/>
          <ownedActivityEdge source="//compare/MocaCompare/collectAddition/@activity/@ownedActivityNode.2" target="//compare/MocaCompare/collectAddition/@activity/@ownedActivityNode.0"/>
          <ownedActivityNode xsi:type="activities:StoryNode" name="collect addition" comment="collect_addition" outgoing="//compare/MocaCompare/collectAddition/@activity/@ownedActivityEdge.0" incoming="//compare/MocaCompare/collectAddition/@activity/@ownedActivityEdge.1">
            <storyPattern comment="collect_addition">
              <objectVariable type="//compare/Addition" name="addition" incomingLink="//compare/MocaCompare/collectAddition/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.2" outgoingLink="//compare/MocaCompare/collectAddition/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.0 //compare/MocaCompare/collectAddition/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.1" bindingOperator="CREATE"/>
              <objectVariable name="element" incomingLink="//compare/MocaCompare/collectAddition/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.0" bindingState="BOUND">
                <type xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//TreeElement"/>
              </objectVariable>
              <objectVariable name="leftParent" incomingLink="//compare/MocaCompare/collectAddition/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.1" bindingState="BOUND">
                <type xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//TreeElement"/>
              </objectVariable>
              <objectVariable type="//compare/MocaCompare" name="this" outgoingLink="//compare/MocaCompare/collectAddition/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.2" bindingState="BOUND"/>
              <linkVariable name="element" target="//compare/MocaCompare/collectAddition/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.1" source="//compare/MocaCompare/collectAddition/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.0" type="//compare/MocaDiff/element" bindingOperator="CREATE"/>
              <linkVariable name="leftParent" target="//compare/MocaCompare/collectAddition/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.2" source="//compare/MocaCompare/collectAddition/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.0" type="//compare/MocaDiff/leftParent" bindingOperator="CREATE"/>
              <linkVariable name="addition" target="//compare/MocaCompare/collectAddition/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.0" source="//compare/MocaCompare/collectAddition/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.3" type="//compare/MocaCompare/addition" bindingOperator="CREATE"/>
            </storyPattern>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StopNode" incoming="//compare/MocaCompare/collectAddition/@activity/@ownedActivityEdge.0"/>
          <ownedActivityNode xsi:type="activities:StartNode" outgoing="//compare/MocaCompare/collectAddition/@activity/@ownedActivityEdge.1"/>
        </activity>
      </eOperations>
      <eOperations xsi:type="activities:MoflonEOperation" name="collectDeletion">
        <eParameters name="element">
          <eType xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//TreeElement"/>
        </eParameters>
        <eParameters name="leftParent">
          <eType xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//TreeElement"/>
        </eParameters>
        <activity owningOperation="//compare/MocaCompare/collectDeletion">
          <ownedActivityEdge source="//compare/MocaCompare/collectDeletion/@activity/@ownedActivityNode.0" target="//compare/MocaCompare/collectDeletion/@activity/@ownedActivityNode.1"/>
          <ownedActivityEdge source="//compare/MocaCompare/collectDeletion/@activity/@ownedActivityNode.2" target="//compare/MocaCompare/collectDeletion/@activity/@ownedActivityNode.0"/>
          <ownedActivityNode xsi:type="activities:StoryNode" name="collect deletion" comment="collect_deletion" outgoing="//compare/MocaCompare/collectDeletion/@activity/@ownedActivityEdge.0" incoming="//compare/MocaCompare/collectDeletion/@activity/@ownedActivityEdge.1">
            <storyPattern comment="collect_deletion">
              <objectVariable type="//compare/Deletion" name="deletion" incomingLink="//compare/MocaCompare/collectDeletion/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.2" outgoingLink="//compare/MocaCompare/collectDeletion/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.0 //compare/MocaCompare/collectDeletion/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.1" bindingOperator="CREATE"/>
              <objectVariable name="element" incomingLink="//compare/MocaCompare/collectDeletion/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.1" bindingState="BOUND">
                <type xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//TreeElement"/>
              </objectVariable>
              <objectVariable name="leftParent" incomingLink="//compare/MocaCompare/collectDeletion/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.0" bindingState="BOUND">
                <type xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//TreeElement"/>
              </objectVariable>
              <objectVariable type="//compare/MocaCompare" name="this" outgoingLink="//compare/MocaCompare/collectDeletion/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.2" bindingState="BOUND"/>
              <linkVariable name="leftParent" target="//compare/MocaCompare/collectDeletion/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.2" source="//compare/MocaCompare/collectDeletion/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.0" type="//compare/MocaDiff/leftParent" bindingOperator="CREATE"/>
              <linkVariable name="element" target="//compare/MocaCompare/collectDeletion/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.1" source="//compare/MocaCompare/collectDeletion/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.0" type="//compare/MocaDiff/element" bindingOperator="CREATE"/>
              <linkVariable name="deletion" target="//compare/MocaCompare/collectDeletion/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.0" source="//compare/MocaCompare/collectDeletion/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.3" type="//compare/MocaCompare/deletion" bindingOperator="CREATE"/>
            </storyPattern>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StopNode" incoming="//compare/MocaCompare/collectDeletion/@activity/@ownedActivityEdge.0"/>
          <ownedActivityNode xsi:type="activities:StartNode" outgoing="//compare/MocaCompare/collectDeletion/@activity/@ownedActivityEdge.1"/>
        </activity>
      </eOperations>
      <eOperations xsi:type="activities:MoflonEOperation" name="compare">
        <eParameters name="left">
          <eType xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Folder"/>
        </eParameters>
        <eParameters name="right">
          <eType xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Folder"/>
        </eParameters>
        <activity owningOperation="//compare/MocaCompare/compare">
          <ownedActivityEdge source="//compare/MocaCompare/compare/@activity/@ownedActivityNode.0" target="//compare/MocaCompare/compare/@activity/@ownedActivityNode.1"/>
          <ownedActivityEdge source="//compare/MocaCompare/compare/@activity/@ownedActivityNode.1" target="//compare/MocaCompare/compare/@activity/@ownedActivityNode.3"/>
          <ownedActivityEdge source="//compare/MocaCompare/compare/@activity/@ownedActivityNode.2" target="//compare/MocaCompare/compare/@activity/@ownedActivityNode.0"/>
          <ownedActivityEdge source="//compare/MocaCompare/compare/@activity/@ownedActivityNode.4" target="//compare/MocaCompare/compare/@activity/@ownedActivityNode.2"/>
          <ownedActivityNode xsi:type="activities:StatementNode" name="cache right" outgoing="//compare/MocaCompare/compare/@activity/@ownedActivityEdge.0" incoming="//compare/MocaCompare/compare/@activity/@ownedActivityEdge.2">
            <statementExpression xsi:type="callExpressions:MethodCallExpression" callee="//compare/MocaCompare/cacheRightFolder">
              <ownedParameterBindings parameter="//compare/MocaCompare/cacheRightFolder/right">
                <valueExpression xsi:type="callExpressions:ParameterExpression" parameter="//compare/MocaCompare/compare/right"/>
              </ownedParameterBindings>
              <target xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compare/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.0"/>
            </statementExpression>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StatementNode" name="compare left and right" outgoing="//compare/MocaCompare/compare/@activity/@ownedActivityEdge.1" incoming="//compare/MocaCompare/compare/@activity/@ownedActivityEdge.0">
            <statementExpression xsi:type="callExpressions:MethodCallExpression" callee="//compare/MocaCompare/compareFolder">
              <ownedParameterBindings parameter="//compare/MocaCompare/compareFolder/left">
                <valueExpression xsi:type="callExpressions:ParameterExpression" parameter="//compare/MocaCompare/compare/left"/>
              </ownedParameterBindings>
              <ownedParameterBindings parameter="//compare/MocaCompare/compareFolder/right">
                <valueExpression xsi:type="callExpressions:ParameterExpression" parameter="//compare/MocaCompare/compare/right"/>
              </ownedParameterBindings>
              <target xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compare/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.0"/>
            </statementExpression>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StoryNode" name="match this" comment="match_this" outgoing="//compare/MocaCompare/compare/@activity/@ownedActivityEdge.2" incoming="//compare/MocaCompare/compare/@activity/@ownedActivityEdge.3">
            <storyPattern comment="match_this">
              <objectVariable type="//compare/MocaCompare" name="this" bindingState="BOUND"/>
            </storyPattern>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StopNode" incoming="//compare/MocaCompare/compare/@activity/@ownedActivityEdge.1"/>
          <ownedActivityNode xsi:type="activities:StartNode" outgoing="//compare/MocaCompare/compare/@activity/@ownedActivityEdge.3"/>
        </activity>
      </eOperations>
      <eOperations xsi:type="activities:MoflonEOperation" name="compareFile">
        <eParameters name="left">
          <eType xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//File"/>
        </eParameters>
        <eParameters name="right">
          <eType xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//File"/>
        </eParameters>
        <activity owningOperation="//compare/MocaCompare/compareFile">
          <ownedActivityEdge source="//compare/MocaCompare/compareFile/@activity/@ownedActivityNode.0" target="//compare/MocaCompare/compareFile/@activity/@ownedActivityNode.6"/>
          <ownedActivityEdge source="//compare/MocaCompare/compareFile/@activity/@ownedActivityNode.1" target="//compare/MocaCompare/compareFile/@activity/@ownedActivityNode.2"/>
          <ownedActivityEdge source="//compare/MocaCompare/compareFile/@activity/@ownedActivityNode.2" target="//compare/MocaCompare/compareFile/@activity/@ownedActivityNode.7"/>
          <ownedActivityEdge source="//compare/MocaCompare/compareFile/@activity/@ownedActivityNode.3" target="//compare/MocaCompare/compareFile/@activity/@ownedActivityNode.1"/>
          <ownedActivityEdge source="//compare/MocaCompare/compareFile/@activity/@ownedActivityNode.4" target="//compare/MocaCompare/compareFile/@activity/@ownedActivityNode.3" guard="FAILURE"/>
          <ownedActivityEdge source="//compare/MocaCompare/compareFile/@activity/@ownedActivityNode.4" target="//compare/MocaCompare/compareFile/@activity/@ownedActivityNode.0" guard="SUCCESS"/>
          <ownedActivityEdge source="//compare/MocaCompare/compareFile/@activity/@ownedActivityNode.5" target="//compare/MocaCompare/compareFile/@activity/@ownedActivityNode.4"/>
          <ownedActivityEdge source="//compare/MocaCompare/compareFile/@activity/@ownedActivityNode.8" target="//compare/MocaCompare/compareFile/@activity/@ownedActivityNode.5"/>
          <ownedActivityNode xsi:type="activities:StatementNode" name="CompareRootNodes" outgoing="//compare/MocaCompare/compareFile/@activity/@ownedActivityEdge.0" incoming="//compare/MocaCompare/compareFile/@activity/@ownedActivityEdge.5">
            <statementExpression xsi:type="callExpressions:MethodCallExpression" callee="//compare/MocaCompare/compareNode">
              <ownedParameterBindings parameter="//compare/MocaCompare/compareNode/left">
                <valueExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareFile/@activity/@ownedActivityNode.5/@storyPattern/@objectVariable.1"/>
              </ownedParameterBindings>
              <ownedParameterBindings parameter="//compare/MocaCompare/compareNode/right">
                <valueExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareFile/@activity/@ownedActivityNode.4/@storyPattern/@objectVariable.1"/>
              </ownedParameterBindings>
              <target xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareFile/@activity/@ownedActivityNode.5/@storyPattern/@objectVariable.2"/>
            </statementExpression>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StoryNode" name="CreateDummyRightTreeNode" comment="CreateDummyRightTreeNode" outgoing="//compare/MocaCompare/compareFile/@activity/@ownedActivityEdge.1" incoming="//compare/MocaCompare/compareFile/@activity/@ownedActivityEdge.3">
            <storyPattern comment="CreateDummyRightTreeNode">
              <objectVariable name="rightDummyRoot" bindingOperator="CREATE">
                <type xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Node"/>
                <attributeAssignment>
                  <valueExpression xsi:type="patternExpressions:AttributeValueExpression" object="//compare/MocaCompare/compareFile/@activity/@ownedActivityNode.5/@storyPattern/@objectVariable.1">
                    <attribute href="platform:/plugin/MocaTree/model/MocaTree.ecore#//TreeElement/name"/>
                  </valueExpression>
                  <attribute href="platform:/plugin/MocaTree/model/MocaTree.ecore#//TreeElement/name"/>
                </attributeAssignment>
                <attributeAssignment>
                  <valueExpression xsi:type="patternExpressions:AttributeValueExpression" object="//compare/MocaCompare/compareFile/@activity/@ownedActivityNode.5/@storyPattern/@objectVariable.1">
                    <attribute href="platform:/plugin/MocaTree/model/MocaTree.ecore#//TreeElement/index"/>
                  </valueExpression>
                  <attribute href="platform:/plugin/MocaTree/model/MocaTree.ecore#//TreeElement/index"/>
                </attributeAssignment>
              </objectVariable>
            </storyPattern>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StatementNode" name="collect addition" outgoing="//compare/MocaCompare/compareFile/@activity/@ownedActivityEdge.2" incoming="//compare/MocaCompare/compareFile/@activity/@ownedActivityEdge.1">
            <statementExpression xsi:type="callExpressions:MethodCallExpression" callee="//compare/MocaCompare/collectAddition">
              <ownedParameterBindings parameter="//compare/MocaCompare/collectAddition/element">
                <valueExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareFile/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.0"/>
              </ownedParameterBindings>
              <ownedParameterBindings parameter="//compare/MocaCompare/collectAddition/leftParent">
                <valueExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareFile/@activity/@ownedActivityNode.5/@storyPattern/@objectVariable.0"/>
              </ownedParameterBindings>
              <target xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareFile/@activity/@ownedActivityNode.5/@storyPattern/@objectVariable.2"/>
            </statementExpression>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StatementNode" name="collect deletion" outgoing="//compare/MocaCompare/compareFile/@activity/@ownedActivityEdge.3" incoming="//compare/MocaCompare/compareFile/@activity/@ownedActivityEdge.4">
            <statementExpression xsi:type="callExpressions:MethodCallExpression" callee="//compare/MocaCompare/collectDeletion">
              <ownedParameterBindings parameter="//compare/MocaCompare/collectDeletion/element">
                <valueExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareFile/@activity/@ownedActivityNode.5/@storyPattern/@objectVariable.1"/>
              </ownedParameterBindings>
              <ownedParameterBindings parameter="//compare/MocaCompare/collectDeletion/leftParent">
                <valueExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareFile/@activity/@ownedActivityNode.5/@storyPattern/@objectVariable.0"/>
              </ownedParameterBindings>
              <target xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareFile/@activity/@ownedActivityNode.5/@storyPattern/@objectVariable.2"/>
            </statementExpression>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StoryNode" name="compare to right root node" comment="compare_to_right_root_node" outgoing="//compare/MocaCompare/compareFile/@activity/@ownedActivityEdge.4 //compare/MocaCompare/compareFile/@activity/@ownedActivityEdge.5" incoming="//compare/MocaCompare/compareFile/@activity/@ownedActivityEdge.6">
            <storyPattern comment="compare_to_right_root_node">
              <objectVariable name="right" incomingLink="//compare/MocaCompare/compareFile/@activity/@ownedActivityNode.4/@storyPattern/@linkVariable.0" bindingState="BOUND">
                <type xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//File"/>
              </objectVariable>
              <objectVariable name="rightRoot" incomingLink="//compare/MocaCompare/compareFile/@activity/@ownedActivityNode.4/@storyPattern/@linkVariable.1" outgoingLink="//compare/MocaCompare/compareFile/@activity/@ownedActivityNode.4/@storyPattern/@linkVariable.0" bindingState="BOUND">
                <type xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Node"/>
                <bindingExpression xsi:type="callExpressions:MethodCallExpression" callee="//compare/MocaCompare/getTreeElement">
                  <ownedParameterBindings parameter="//compare/MocaCompare/getTreeElement/parent">
                    <valueExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareFile/@activity/@ownedActivityNode.4/@storyPattern/@objectVariable.0"/>
                  </ownedParameterBindings>
                  <ownedParameterBindings parameter="//compare/MocaCompare/getTreeElement/name">
                    <valueExpression xsi:type="patternExpressions:AttributeValueExpression" object="//compare/MocaCompare/compareFile/@activity/@ownedActivityNode.5/@storyPattern/@objectVariable.1">
                      <attribute href="platform:/plugin/MocaTree/model/MocaTree.ecore#//TreeElement/name"/>
                    </valueExpression>
                  </ownedParameterBindings>
                  <ownedParameterBindings parameter="//compare/MocaCompare/getTreeElement/index">
                    <valueExpression xsi:type="patternExpressions:AttributeValueExpression" object="//compare/MocaCompare/compareFile/@activity/@ownedActivityNode.5/@storyPattern/@objectVariable.1">
                      <attribute href="platform:/plugin/MocaTree/model/MocaTree.ecore#//TreeElement/index"/>
                    </valueExpression>
                  </ownedParameterBindings>
                  <target xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareFile/@activity/@ownedActivityNode.5/@storyPattern/@objectVariable.2"/>
                </bindingExpression>
              </objectVariable>
              <objectVariable type="//compare/MocaCompare" name="this" outgoingLink="//compare/MocaCompare/compareFile/@activity/@ownedActivityNode.4/@storyPattern/@linkVariable.1" bindingState="BOUND"/>
              <linkVariable name="file" target="//compare/MocaCompare/compareFile/@activity/@ownedActivityNode.4/@storyPattern/@objectVariable.0" source="//compare/MocaCompare/compareFile/@activity/@ownedActivityNode.4/@storyPattern/@objectVariable.1">
                <type href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Node/file"/>
              </linkVariable>
              <linkVariable name="foundRightRlements" target="//compare/MocaCompare/compareFile/@activity/@ownedActivityNode.4/@storyPattern/@objectVariable.1" source="//compare/MocaCompare/compareFile/@activity/@ownedActivityNode.4/@storyPattern/@objectVariable.2" type="//compare/MocaCompare/foundRightRlements" bindingOperator="CREATE"/>
            </storyPattern>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StoryNode" name="match root node" comment="match_root_node" outgoing="//compare/MocaCompare/compareFile/@activity/@ownedActivityEdge.6" incoming="//compare/MocaCompare/compareFile/@activity/@ownedActivityEdge.7">
            <storyPattern comment="match_root_node">
              <objectVariable name="left" incomingLink="//compare/MocaCompare/compareFile/@activity/@ownedActivityNode.5/@storyPattern/@linkVariable.0" bindingState="BOUND">
                <type xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//File"/>
              </objectVariable>
              <objectVariable name="leftRoot" outgoingLink="//compare/MocaCompare/compareFile/@activity/@ownedActivityNode.5/@storyPattern/@linkVariable.0">
                <type xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Node"/>
              </objectVariable>
              <objectVariable type="//compare/MocaCompare" name="this" bindingState="BOUND"/>
              <linkVariable name="file" target="//compare/MocaCompare/compareFile/@activity/@ownedActivityNode.5/@storyPattern/@objectVariable.0" source="//compare/MocaCompare/compareFile/@activity/@ownedActivityNode.5/@storyPattern/@objectVariable.1">
                <type href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Node/file"/>
              </linkVariable>
            </storyPattern>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StopNode" incoming="//compare/MocaCompare/compareFile/@activity/@ownedActivityEdge.0"/>
          <ownedActivityNode xsi:type="activities:StopNode" incoming="//compare/MocaCompare/compareFile/@activity/@ownedActivityEdge.2"/>
          <ownedActivityNode xsi:type="activities:StartNode" outgoing="//compare/MocaCompare/compareFile/@activity/@ownedActivityEdge.7"/>
        </activity>
      </eOperations>
      <eOperations xsi:type="activities:MoflonEOperation" name="compareFolder">
        <eParameters name="left">
          <eType xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Folder"/>
        </eParameters>
        <eParameters name="right">
          <eType xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Folder"/>
        </eParameters>
        <activity owningOperation="//compare/MocaCompare/compareFolder">
          <ownedActivityEdge source="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.0" target="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.9"/>
          <ownedActivityEdge source="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.1" target="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.12" guard="END"/>
          <ownedActivityEdge source="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.1" target="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.3" guard="EACH_TIME"/>
          <ownedActivityEdge source="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.2" target="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.1" guard="END"/>
          <ownedActivityEdge source="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.2" target="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.4" guard="EACH_TIME"/>
          <ownedActivityEdge source="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.3" target="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.1"/>
          <ownedActivityEdge source="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.4" target="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.2"/>
          <ownedActivityEdge source="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.5" target="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.10"/>
          <ownedActivityEdge source="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.6" target="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.9"/>
          <ownedActivityEdge source="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.7" target="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.0" guard="SUCCESS"/>
          <ownedActivityEdge source="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.7" target="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.6" guard="FAILURE"/>
          <ownedActivityEdge source="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.8" target="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.11" guard="SUCCESS"/>
          <ownedActivityEdge source="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.8" target="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.5" guard="FAILURE"/>
          <ownedActivityEdge source="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.9" target="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.7" guard="EACH_TIME"/>
          <ownedActivityEdge source="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.9" target="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.2" guard="END"/>
          <ownedActivityEdge source="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.10" target="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.9" guard="END"/>
          <ownedActivityEdge source="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.10" target="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.8" guard="EACH_TIME"/>
          <ownedActivityEdge source="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.11" target="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.10"/>
          <ownedActivityEdge source="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.13" target="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.10"/>
          <ownedActivityNode xsi:type="activities:StatementNode" name="call for file" outgoing="//compare/MocaCompare/compareFolder/@activity/@ownedActivityEdge.0" incoming="//compare/MocaCompare/compareFolder/@activity/@ownedActivityEdge.9">
            <statementExpression xsi:type="callExpressions:MethodCallExpression" callee="//compare/MocaCompare/compareFile">
              <ownedParameterBindings parameter="//compare/MocaCompare/compareFile/left">
                <valueExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.7/@storyPattern/@objectVariable.0"/>
              </ownedParameterBindings>
              <ownedParameterBindings parameter="//compare/MocaCompare/compareFile/right">
                <valueExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.7/@storyPattern/@objectVariable.2"/>
              </ownedParameterBindings>
              <target xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.7/@storyPattern/@objectVariable.3"/>
            </statementExpression>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StoryNode" name="collect added file" comment="collect_added_file" outgoing="//compare/MocaCompare/compareFolder/@activity/@ownedActivityEdge.1 //compare/MocaCompare/compareFolder/@activity/@ownedActivityEdge.2" incoming="//compare/MocaCompare/compareFolder/@activity/@ownedActivityEdge.3 //compare/MocaCompare/compareFolder/@activity/@ownedActivityEdge.5" forEach="true">
            <storyPattern comment="collect_added_file">
              <objectVariable name="addedFile" incomingLink="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.0 //compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.1">
                <type xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//File"/>
              </objectVariable>
              <objectVariable name="right" outgoingLink="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.0" bindingState="BOUND">
                <type xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Folder"/>
              </objectVariable>
              <objectVariable type="//compare/MocaCompare" name="this" outgoingLink="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.1" bindingState="BOUND"/>
              <linkVariable name="file" target="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.0" source="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.1">
                <type href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Folder/file"/>
              </linkVariable>
              <linkVariable name="foundRightRlements" target="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.0" source="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.2" type="//compare/MocaCompare/foundRightRlements" bindingSemantics="NEGATIVE"/>
            </storyPattern>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StoryNode" name="collect added sub fodlers" comment="collect_added_sub_fodlers" outgoing="//compare/MocaCompare/compareFolder/@activity/@ownedActivityEdge.3 //compare/MocaCompare/compareFolder/@activity/@ownedActivityEdge.4" incoming="//compare/MocaCompare/compareFolder/@activity/@ownedActivityEdge.6 //compare/MocaCompare/compareFolder/@activity/@ownedActivityEdge.14" forEach="true">
            <storyPattern comment="collect_added_sub_fodlers">
              <objectVariable name="addedSub" incomingLink="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.2/@storyPattern/@linkVariable.1" outgoingLink="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.2/@storyPattern/@linkVariable.0">
                <type xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Folder"/>
              </objectVariable>
              <objectVariable name="right" incomingLink="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.2/@storyPattern/@linkVariable.0" bindingState="BOUND">
                <type xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Folder"/>
              </objectVariable>
              <objectVariable type="//compare/MocaCompare" name="this" outgoingLink="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.2/@storyPattern/@linkVariable.1" bindingState="BOUND"/>
              <linkVariable name="parentFolder" target="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.1" source="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.0">
                <type href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Folder/parentFolder"/>
              </linkVariable>
              <linkVariable name="foundRightRlements" target="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.0" source="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.2" type="//compare/MocaCompare/foundRightRlements" bindingSemantics="NEGATIVE"/>
            </storyPattern>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StatementNode" name="collect addition" outgoing="//compare/MocaCompare/compareFolder/@activity/@ownedActivityEdge.5" incoming="//compare/MocaCompare/compareFolder/@activity/@ownedActivityEdge.2">
            <statementExpression xsi:type="callExpressions:MethodCallExpression" callee="//compare/MocaCompare/collectAddition">
              <ownedParameterBindings parameter="//compare/MocaCompare/collectAddition/element">
                <valueExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.0"/>
              </ownedParameterBindings>
              <ownedParameterBindings parameter="//compare/MocaCompare/collectAddition/leftParent">
                <valueExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.10/@storyPattern/@objectVariable.0"/>
              </ownedParameterBindings>
              <target xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.7/@storyPattern/@objectVariable.3"/>
            </statementExpression>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StatementNode" name="collect addition" outgoing="//compare/MocaCompare/compareFolder/@activity/@ownedActivityEdge.6" incoming="//compare/MocaCompare/compareFolder/@activity/@ownedActivityEdge.4">
            <statementExpression xsi:type="callExpressions:MethodCallExpression" callee="//compare/MocaCompare/collectAddition">
              <ownedParameterBindings parameter="//compare/MocaCompare/collectAddition/element">
                <valueExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.0"/>
              </ownedParameterBindings>
              <ownedParameterBindings parameter="//compare/MocaCompare/collectAddition/leftParent">
                <valueExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.10/@storyPattern/@objectVariable.0"/>
              </ownedParameterBindings>
              <target xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.7/@storyPattern/@objectVariable.3"/>
            </statementExpression>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StatementNode" name="collect deletion" outgoing="//compare/MocaCompare/compareFolder/@activity/@ownedActivityEdge.7" incoming="//compare/MocaCompare/compareFolder/@activity/@ownedActivityEdge.12">
            <statementExpression xsi:type="callExpressions:MethodCallExpression" callee="//compare/MocaCompare/collectDeletion">
              <ownedParameterBindings parameter="//compare/MocaCompare/collectDeletion/element">
                <valueExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.10/@storyPattern/@objectVariable.1"/>
              </ownedParameterBindings>
              <ownedParameterBindings parameter="//compare/MocaCompare/collectDeletion/leftParent">
                <valueExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.10/@storyPattern/@objectVariable.0"/>
              </ownedParameterBindings>
              <target xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.7/@storyPattern/@objectVariable.3"/>
            </statementExpression>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StatementNode" name="collect deletion" outgoing="//compare/MocaCompare/compareFolder/@activity/@ownedActivityEdge.8" incoming="//compare/MocaCompare/compareFolder/@activity/@ownedActivityEdge.10">
            <statementExpression xsi:type="callExpressions:MethodCallExpression" callee="//compare/MocaCompare/collectDeletion">
              <ownedParameterBindings parameter="//compare/MocaCompare/collectDeletion/element">
                <valueExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.7/@storyPattern/@objectVariable.0"/>
              </ownedParameterBindings>
              <ownedParameterBindings parameter="//compare/MocaCompare/collectDeletion/leftParent">
                <valueExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.10/@storyPattern/@objectVariable.0"/>
              </ownedParameterBindings>
              <target xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.7/@storyPattern/@objectVariable.3"/>
            </statementExpression>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StoryNode" name="find a corresponding file on right" comment="find_a_corresponding_file_on_right" outgoing="//compare/MocaCompare/compareFolder/@activity/@ownedActivityEdge.9 //compare/MocaCompare/compareFolder/@activity/@ownedActivityEdge.10" incoming="//compare/MocaCompare/compareFolder/@activity/@ownedActivityEdge.13">
            <storyPattern comment="find_a_corresponding_file_on_right">
              <objectVariable name="leftFile" bindingState="BOUND">
                <type xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//File"/>
              </objectVariable>
              <objectVariable name="right" outgoingLink="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.7/@storyPattern/@linkVariable.0" bindingState="BOUND">
                <type xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Folder"/>
              </objectVariable>
              <objectVariable name="rightFile" incomingLink="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.7/@storyPattern/@linkVariable.1 //compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.7/@storyPattern/@linkVariable.0" bindingState="BOUND">
                <type xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//File"/>
                <bindingExpression xsi:type="callExpressions:MethodCallExpression" callee="//compare/MocaCompare/getTreeElement">
                  <ownedParameterBindings parameter="//compare/MocaCompare/getTreeElement/parent">
                    <valueExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.7/@storyPattern/@objectVariable.1"/>
                  </ownedParameterBindings>
                  <ownedParameterBindings parameter="//compare/MocaCompare/getTreeElement/name">
                    <valueExpression xsi:type="patternExpressions:AttributeValueExpression" object="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.7/@storyPattern/@objectVariable.0">
                      <attribute href="platform:/plugin/MocaTree/model/MocaTree.ecore#//TreeElement/name"/>
                    </valueExpression>
                  </ownedParameterBindings>
                  <ownedParameterBindings parameter="//compare/MocaCompare/getTreeElement/index">
                    <valueExpression xsi:type="patternExpressions:AttributeValueExpression" object="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.7/@storyPattern/@objectVariable.0">
                      <attribute href="platform:/plugin/MocaTree/model/MocaTree.ecore#//TreeElement/index"/>
                    </valueExpression>
                  </ownedParameterBindings>
                  <target xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.7/@storyPattern/@objectVariable.3"/>
                </bindingExpression>
              </objectVariable>
              <objectVariable type="//compare/MocaCompare" name="this" outgoingLink="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.7/@storyPattern/@linkVariable.1" bindingState="BOUND"/>
              <linkVariable name="file" target="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.7/@storyPattern/@objectVariable.2" source="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.7/@storyPattern/@objectVariable.1">
                <type href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Folder/file"/>
              </linkVariable>
              <linkVariable name="foundRightRlements" target="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.7/@storyPattern/@objectVariable.2" source="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.7/@storyPattern/@objectVariable.3" type="//compare/MocaCompare/foundRightRlements" bindingOperator="CREATE"/>
            </storyPattern>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StoryNode" name="find a corresponding folder on right" comment="find_a_corresponding_folder_on_right" outgoing="//compare/MocaCompare/compareFolder/@activity/@ownedActivityEdge.11 //compare/MocaCompare/compareFolder/@activity/@ownedActivityEdge.12" incoming="//compare/MocaCompare/compareFolder/@activity/@ownedActivityEdge.16">
            <storyPattern comment="find_a_corresponding_folder_on_right">
              <objectVariable name="right" outgoingLink="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.8/@storyPattern/@linkVariable.0" bindingState="BOUND">
                <type xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Folder"/>
              </objectVariable>
              <objectVariable name="subRight" incomingLink="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.8/@storyPattern/@linkVariable.0 //compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.8/@storyPattern/@linkVariable.1" bindingState="BOUND">
                <type xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Folder"/>
                <bindingExpression xsi:type="callExpressions:MethodCallExpression" callee="//compare/MocaCompare/getTreeElement">
                  <ownedParameterBindings parameter="//compare/MocaCompare/getTreeElement/parent">
                    <valueExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.7/@storyPattern/@objectVariable.1"/>
                  </ownedParameterBindings>
                  <ownedParameterBindings parameter="//compare/MocaCompare/getTreeElement/name">
                    <valueExpression xsi:type="patternExpressions:AttributeValueExpression" object="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.10/@storyPattern/@objectVariable.1">
                      <attribute href="platform:/plugin/MocaTree/model/MocaTree.ecore#//TreeElement/name"/>
                    </valueExpression>
                  </ownedParameterBindings>
                  <ownedParameterBindings parameter="//compare/MocaCompare/getTreeElement/index">
                    <valueExpression xsi:type="patternExpressions:AttributeValueExpression" object="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.10/@storyPattern/@objectVariable.1">
                      <attribute href="platform:/plugin/MocaTree/model/MocaTree.ecore#//TreeElement/index"/>
                    </valueExpression>
                  </ownedParameterBindings>
                  <target xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.7/@storyPattern/@objectVariable.3"/>
                </bindingExpression>
              </objectVariable>
              <objectVariable type="//compare/MocaCompare" name="this" outgoingLink="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.8/@storyPattern/@linkVariable.1" bindingState="BOUND"/>
              <linkVariable name="subFolder" target="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.8/@storyPattern/@objectVariable.1" source="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.8/@storyPattern/@objectVariable.0">
                <type href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Folder/subFolder"/>
              </linkVariable>
              <linkVariable name="foundRightRlements" target="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.8/@storyPattern/@objectVariable.1" source="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.8/@storyPattern/@objectVariable.2" type="//compare/MocaCompare/foundRightRlements" bindingOperator="CREATE"/>
            </storyPattern>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StoryNode" name="iterate over files" comment="iterate_over_files" outgoing="//compare/MocaCompare/compareFolder/@activity/@ownedActivityEdge.13 //compare/MocaCompare/compareFolder/@activity/@ownedActivityEdge.14" incoming="//compare/MocaCompare/compareFolder/@activity/@ownedActivityEdge.0 //compare/MocaCompare/compareFolder/@activity/@ownedActivityEdge.8 //compare/MocaCompare/compareFolder/@activity/@ownedActivityEdge.15" forEach="true">
            <storyPattern comment="iterate_over_files">
              <objectVariable name="left" outgoingLink="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.9/@storyPattern/@linkVariable.0" bindingState="BOUND">
                <type xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Folder"/>
              </objectVariable>
              <objectVariable name="leftFile" incomingLink="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.9/@storyPattern/@linkVariable.0">
                <type xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//File"/>
              </objectVariable>
              <linkVariable name="file" target="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.9/@storyPattern/@objectVariable.1" source="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.9/@storyPattern/@objectVariable.0">
                <type href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Folder/file"/>
              </linkVariable>
            </storyPattern>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StoryNode" name="iterate over subfolders" comment="iterate_over_subfolders" outgoing="//compare/MocaCompare/compareFolder/@activity/@ownedActivityEdge.15 //compare/MocaCompare/compareFolder/@activity/@ownedActivityEdge.16" incoming="//compare/MocaCompare/compareFolder/@activity/@ownedActivityEdge.7 //compare/MocaCompare/compareFolder/@activity/@ownedActivityEdge.17 //compare/MocaCompare/compareFolder/@activity/@ownedActivityEdge.18" forEach="true">
            <storyPattern comment="iterate_over_subfolders">
              <objectVariable name="left" outgoingLink="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.10/@storyPattern/@linkVariable.0" bindingState="BOUND">
                <type xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Folder"/>
              </objectVariable>
              <objectVariable name="subLeft" incomingLink="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.10/@storyPattern/@linkVariable.0">
                <type xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Folder"/>
              </objectVariable>
              <linkVariable name="subFolder" target="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.10/@storyPattern/@objectVariable.1" source="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.10/@storyPattern/@objectVariable.0">
                <type href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Folder/subFolder"/>
              </linkVariable>
            </storyPattern>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StatementNode" name="recursive call for sub folders" outgoing="//compare/MocaCompare/compareFolder/@activity/@ownedActivityEdge.17" incoming="//compare/MocaCompare/compareFolder/@activity/@ownedActivityEdge.11">
            <statementExpression xsi:type="callExpressions:MethodCallExpression" callee="//compare/MocaCompare/compareFolder">
              <ownedParameterBindings parameter="//compare/MocaCompare/compareFolder/left">
                <valueExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.10/@storyPattern/@objectVariable.1"/>
              </ownedParameterBindings>
              <ownedParameterBindings parameter="//compare/MocaCompare/compareFolder/right">
                <valueExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.8/@storyPattern/@objectVariable.1"/>
              </ownedParameterBindings>
              <target xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareFolder/@activity/@ownedActivityNode.8/@storyPattern/@objectVariable.2"/>
            </statementExpression>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StopNode" incoming="//compare/MocaCompare/compareFolder/@activity/@ownedActivityEdge.1"/>
          <ownedActivityNode xsi:type="activities:StartNode" outgoing="//compare/MocaCompare/compareFolder/@activity/@ownedActivityEdge.18"/>
        </activity>
      </eOperations>
      <eOperations xsi:type="activities:MoflonEOperation" name="compareNode">
        <eParameters name="left">
          <eType xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Node"/>
        </eParameters>
        <eParameters name="right">
          <eType xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Node"/>
        </eParameters>
        <activity owningOperation="//compare/MocaCompare/compareNode">
          <ownedActivityEdge source="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.0" target="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.4"/>
          <ownedActivityEdge source="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.1" target="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.5"/>
          <ownedActivityEdge source="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.2" target="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.5"/>
          <ownedActivityEdge source="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.3" target="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.1" guard="FAILURE"/>
          <ownedActivityEdge source="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.3" target="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.2" guard="SUCCESS"/>
          <ownedActivityEdge source="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.4" target="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.6" guard="END"/>
          <ownedActivityEdge source="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.4" target="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.0" guard="EACH_TIME"/>
          <ownedActivityEdge source="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.5" target="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.4" guard="END"/>
          <ownedActivityEdge source="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.5" target="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.3" guard="EACH_TIME"/>
          <ownedActivityEdge source="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.7" target="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.5"/>
          <ownedActivityNode xsi:type="activities:StatementNode" name="collect addition" outgoing="//compare/MocaCompare/compareNode/@activity/@ownedActivityEdge.0" incoming="//compare/MocaCompare/compareNode/@activity/@ownedActivityEdge.6">
            <statementExpression xsi:type="callExpressions:MethodCallExpression" callee="//compare/MocaCompare/collectAddition">
              <ownedParameterBindings parameter="//compare/MocaCompare/collectAddition/element">
                <valueExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.4/@storyPattern/@objectVariable.0"/>
              </ownedParameterBindings>
              <ownedParameterBindings parameter="//compare/MocaCompare/collectAddition/leftParent">
                <valueExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.5/@storyPattern/@objectVariable.0"/>
              </ownedParameterBindings>
              <target xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.4/@storyPattern/@objectVariable.2"/>
            </statementExpression>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StatementNode" name="collect deletion" outgoing="//compare/MocaCompare/compareNode/@activity/@ownedActivityEdge.1" incoming="//compare/MocaCompare/compareNode/@activity/@ownedActivityEdge.3">
            <statementExpression xsi:type="callExpressions:MethodCallExpression" callee="//compare/MocaCompare/collectDeletion">
              <ownedParameterBindings parameter="//compare/MocaCompare/collectDeletion/element">
                <valueExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.5/@storyPattern/@objectVariable.1"/>
              </ownedParameterBindings>
              <ownedParameterBindings parameter="//compare/MocaCompare/collectDeletion/leftParent">
                <valueExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.5/@storyPattern/@objectVariable.0"/>
              </ownedParameterBindings>
              <target xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.3/@storyPattern/@objectVariable.2"/>
            </statementExpression>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StatementNode" name="compare children recursively" outgoing="//compare/MocaCompare/compareNode/@activity/@ownedActivityEdge.2" incoming="//compare/MocaCompare/compareNode/@activity/@ownedActivityEdge.4">
            <statementExpression xsi:type="callExpressions:MethodCallExpression" callee="//compare/MocaCompare/compareNode">
              <ownedParameterBindings parameter="//compare/MocaCompare/compareNode/left">
                <valueExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.5/@storyPattern/@objectVariable.1"/>
              </ownedParameterBindings>
              <ownedParameterBindings parameter="//compare/MocaCompare/compareNode/right">
                <valueExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.3/@storyPattern/@objectVariable.1"/>
              </ownedParameterBindings>
              <target xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.3/@storyPattern/@objectVariable.2"/>
            </statementExpression>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StoryNode" name="find a corresponding child on the right" comment="find_a_corresponding_child_on_the_right" outgoing="//compare/MocaCompare/compareNode/@activity/@ownedActivityEdge.3 //compare/MocaCompare/compareNode/@activity/@ownedActivityEdge.4" incoming="//compare/MocaCompare/compareNode/@activity/@ownedActivityEdge.8">
            <storyPattern comment="find_a_corresponding_child_on_the_right">
              <objectVariable name="right" incomingLink="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.3/@storyPattern/@linkVariable.0" bindingState="BOUND">
                <type xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Node"/>
              </objectVariable>
              <objectVariable name="rightChild" incomingLink="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.3/@storyPattern/@linkVariable.1" outgoingLink="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.3/@storyPattern/@linkVariable.0" bindingState="BOUND">
                <type xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Node"/>
                <bindingExpression xsi:type="callExpressions:MethodCallExpression" callee="//compare/MocaCompare/getTreeElement">
                  <ownedParameterBindings parameter="//compare/MocaCompare/getTreeElement/parent">
                    <valueExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.3/@storyPattern/@objectVariable.0"/>
                  </ownedParameterBindings>
                  <ownedParameterBindings parameter="//compare/MocaCompare/getTreeElement/name">
                    <valueExpression xsi:type="patternExpressions:AttributeValueExpression" object="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.5/@storyPattern/@objectVariable.1">
                      <attribute href="platform:/plugin/MocaTree/model/MocaTree.ecore#//TreeElement/name"/>
                    </valueExpression>
                  </ownedParameterBindings>
                  <ownedParameterBindings parameter="//compare/MocaCompare/getTreeElement/index">
                    <valueExpression xsi:type="patternExpressions:AttributeValueExpression" object="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.5/@storyPattern/@objectVariable.1">
                      <attribute href="platform:/plugin/MocaTree/model/MocaTree.ecore#//TreeElement/index"/>
                    </valueExpression>
                  </ownedParameterBindings>
                  <target xsi:type="patternExpressions:ObjectVariableExpression" object="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.3/@storyPattern/@objectVariable.2"/>
                </bindingExpression>
              </objectVariable>
              <objectVariable type="//compare/MocaCompare" name="this" outgoingLink="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.3/@storyPattern/@linkVariable.1" bindingState="BOUND"/>
              <linkVariable name="parentNode" target="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.3/@storyPattern/@objectVariable.0" source="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.3/@storyPattern/@objectVariable.1">
                <type href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Text/parentNode"/>
              </linkVariable>
              <linkVariable name="foundRightRlements" target="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.3/@storyPattern/@objectVariable.1" source="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.3/@storyPattern/@objectVariable.2" type="//compare/MocaCompare/foundRightRlements" bindingOperator="CREATE"/>
            </storyPattern>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StoryNode" name="iterate over added children" comment="iterate_over_added_children" outgoing="//compare/MocaCompare/compareNode/@activity/@ownedActivityEdge.5 //compare/MocaCompare/compareNode/@activity/@ownedActivityEdge.6" incoming="//compare/MocaCompare/compareNode/@activity/@ownedActivityEdge.0 //compare/MocaCompare/compareNode/@activity/@ownedActivityEdge.7" forEach="true">
            <storyPattern comment="iterate_over_added_children">
              <objectVariable name="addedChild" incomingLink="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.4/@storyPattern/@linkVariable.1" outgoingLink="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.4/@storyPattern/@linkVariable.0">
                <type xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Node"/>
              </objectVariable>
              <objectVariable name="right" incomingLink="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.4/@storyPattern/@linkVariable.0" bindingState="BOUND">
                <type xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Node"/>
              </objectVariable>
              <objectVariable type="//compare/MocaCompare" name="this" outgoingLink="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.4/@storyPattern/@linkVariable.1" bindingState="BOUND"/>
              <linkVariable name="parentNode" target="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.4/@storyPattern/@objectVariable.1" source="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.4/@storyPattern/@objectVariable.0">
                <type href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Text/parentNode"/>
              </linkVariable>
              <linkVariable name="foundRightRlements" target="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.4/@storyPattern/@objectVariable.0" source="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.4/@storyPattern/@objectVariable.2" type="//compare/MocaCompare/foundRightRlements" bindingSemantics="NEGATIVE"/>
            </storyPattern>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StoryNode" name="iterate over children" comment="iterate_over_children" outgoing="//compare/MocaCompare/compareNode/@activity/@ownedActivityEdge.7 //compare/MocaCompare/compareNode/@activity/@ownedActivityEdge.8" incoming="//compare/MocaCompare/compareNode/@activity/@ownedActivityEdge.1 //compare/MocaCompare/compareNode/@activity/@ownedActivityEdge.2 //compare/MocaCompare/compareNode/@activity/@ownedActivityEdge.9" forEach="true">
            <storyPattern comment="iterate_over_children">
              <objectVariable name="left" incomingLink="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.5/@storyPattern/@linkVariable.0" bindingState="BOUND">
                <type xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Node"/>
              </objectVariable>
              <objectVariable name="leftChild" outgoingLink="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.5/@storyPattern/@linkVariable.0">
                <type xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Node"/>
              </objectVariable>
              <linkVariable name="parentNode" target="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.5/@storyPattern/@objectVariable.0" source="//compare/MocaCompare/compareNode/@activity/@ownedActivityNode.5/@storyPattern/@objectVariable.1">
                <type href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Text/parentNode"/>
              </linkVariable>
            </storyPattern>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StopNode" incoming="//compare/MocaCompare/compareNode/@activity/@ownedActivityEdge.5"/>
          <ownedActivityNode xsi:type="activities:StartNode" outgoing="//compare/MocaCompare/compareNode/@activity/@ownedActivityEdge.9"/>
        </activity>
      </eOperations>
      <eOperations xsi:type="activities:MoflonEOperation" name="getTreeElement">
        <eType xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//TreeElement"/>
        <eParameters name="parent">
          <eType xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//TreeElement"/>
        </eParameters>
        <eParameters name="name">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eParameters>
        <eParameters name="index">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="addition" upperBound="-1" eType="//compare/Addition" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="deletion" upperBound="-1" eType="//compare/Deletion" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="foundRightRlements" upperBound="-1">
        <eType xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//TreeElement"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MocaDiff" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="element">
        <eType xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//TreeElement"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="leftParent">
        <eType xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//TreeElement"/>
      </eStructuralFeatures>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="parser" nsURI="platform:/plugin/org.moflon.core.moca.processing/model/Processing.ecore#//parser" nsPrefix="parser">
    <eClassifiers xsi:type="ecore:EClass" name="Parser" abstract="true">
      <eOperations xsi:type="activities:MoflonEOperation" name="canParseFile">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eParameters name="fileName">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eParameters>
      </eOperations>
      <eOperations xsi:type="activities:MoflonEOperation" name="parse">
        <eType xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Node"/>
        <eParameters name="reader" eType="//Reader"/>
      </eOperations>
      <eOperations xsi:type="activities:MoflonEOperation" name="parse">
        <eType xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Node"/>
        <eParameters name="file" eType="//File"/>
        <eParameters name="reader" eType="//Reader"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="codeAdapter" lowerBound="1" eType="//CodeAdapter" eOpposite="//CodeAdapter/parser"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XMLParser" eSuperTypes="//parser/Parser">
      <eOperations xsi:type="activities:MoflonEOperation" name="canParseFile">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eParameters name="fileName">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eParameters>
      </eOperations>
      <eOperations xsi:type="activities:MoflonEOperation" name="parse">
        <eType xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Node"/>
        <eParameters name="reader" eType="//Reader"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ignoreWhitespaces" ordered="false" lowerBound="1" defaultValueLiteral="true">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eStructuralFeatures>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="unparser" nsURI="platform:/plugin/org.moflon.core.moca.processing/model/Processing.ecore#//unparser" nsPrefix="unparser">
    <eClassifiers xsi:type="ecore:EClass" name="TemplateUnparser" abstract="true" eSuperTypes="//unparser/Unparser">
      <eOperations xsi:type="activities:MoflonEOperation" name="unparse">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="node">
          <eType xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Node"/>
        </eParameters>
      </eOperations>
      <eOperations xsi:type="activities:MoflonEOperation" name="canUnparseFile">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eParameters name="fileName">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Unparser" abstract="true">
      <eOperations xsi:type="activities:MoflonEOperation" name="unparse">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="node">
          <eType xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Node"/>
        </eParameters>
      </eOperations>
      <eOperations xsi:type="activities:MoflonEOperation" name="canUnparseFile">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eParameters name="fileName">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eParameters>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="codeAdapter" lowerBound="1" eType="//CodeAdapter" eOpposite="//CodeAdapter/unparser"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XMLUnparser" abstract="true" eSuperTypes="//unparser/TemplateUnparser">
      <eOperations xsi:type="activities:MoflonEOperation" name="unparse">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="node">
          <eType xsi:type="ecore:EClass" href="platform:/plugin/MocaTree/model/MocaTree.ecore#//Node"/>
        </eParameters>
      </eOperations>
      <eOperations xsi:type="activities:MoflonEOperation" name="canUnparseFile">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eParameters name="fileName">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
