/*
 * generated by Xtext 2.11.0
 */
package org.moflon.tie.gt.mosl.controlflow.language

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MOSLControlFlowRuntimeModule extends AbstractMOSLControlFlowRuntimeModule {
}
