/*
 * generated by Xtext 2.11.0
 */
package org.moflon.tie.gt.mosl.controlflow.language

import org.moflon.tie.gt.mosl.controlflow.language.MOSLControlFlowStandaloneSetupGenerated

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MOSLControlFlowStandaloneSetup extends MOSLControlFlowStandaloneSetupGenerated {

	def static void doSetup() {
		new MOSLControlFlowStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}

