<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:activities="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//activities" xmlns:callExpressions="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//calls/callExpressions" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:expressions="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//expressions" xmlns:patternExpressions="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//patterns/patternExpressions" name="dfs" nsURI="platform:/plugin/org.moflon.core.dfs/model/Dfs.ecore" nsPrefix="org.moflon.core.dfs">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="basePackage" value="org.moflon.core"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="EdgeProcessor" abstract="true">
    <eOperations xsi:type="activities:MoflonEOperation" name="processEdge">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eParameters name="edge" eType="//Edge"/>
      <activity owningOperation="//EdgeProcessor/processEdge">
        <ownedActivityEdge source="//EdgeProcessor/processEdge/@activity/@ownedActivityNode.2" target="//EdgeProcessor/processEdge/@activity/@ownedActivityNode.1" guard="FAILURE"/>
        <ownedActivityEdge source="//EdgeProcessor/processEdge/@activity/@ownedActivityNode.2" target="//EdgeProcessor/processEdge/@activity/@ownedActivityNode.0" guard="SUCCESS"/>
        <ownedActivityEdge source="//EdgeProcessor/processEdge/@activity/@ownedActivityNode.4" target="//EdgeProcessor/processEdge/@activity/@ownedActivityNode.3" guard="FAILURE"/>
        <ownedActivityEdge source="//EdgeProcessor/processEdge/@activity/@ownedActivityNode.4" target="//EdgeProcessor/processEdge/@activity/@ownedActivityNode.2" guard="SUCCESS"/>
        <ownedActivityEdge source="//EdgeProcessor/processEdge/@activity/@ownedActivityNode.5" target="//EdgeProcessor/processEdge/@activity/@ownedActivityNode.4"/>
        <ownedActivityNode xsi:type="activities:StopNode" incoming="//EdgeProcessor/processEdge/@activity/@ownedActivityEdge.1">
          <returnValue xsi:type="patternExpressions:ObjectVariableExpression" object="//EdgeProcessor/processEdge/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.0"/>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StopNode" incoming="//EdgeProcessor/processEdge/@activity/@ownedActivityEdge.0">
          <returnValue xsi:type="expressions:LiteralExpression" value="null"/>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StoryNode" name="Delegation" comment="Delegation" outgoing="//EdgeProcessor/processEdge/@activity/@ownedActivityEdge.0 //EdgeProcessor/processEdge/@activity/@ownedActivityEdge.1" incoming="//EdgeProcessor/processEdge/@activity/@ownedActivityEdge.3">
          <storyPattern comment="Delegation">
            <objectVariable name="result" bindingState="BOUND">
              <type xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
              <bindingExpression xsi:type="callExpressions:MethodCallExpression" callee="//EdgeProcessor/processEdge">
                <ownedParameterBindings parameter="//EdgeProcessor/processEdge/edge">
                  <valueExpression xsi:type="callExpressions:ParameterExpression" parameter="//EdgeProcessor/processEdge/edge"/>
                </ownedParameterBindings>
                <target xsi:type="patternExpressions:ObjectVariableExpression" object="//EdgeProcessor/processEdge/@activity/@ownedActivityNode.4/@storyPattern/@objectVariable.1"/>
              </bindingExpression>
            </objectVariable>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StopNode" incoming="//EdgeProcessor/processEdge/@activity/@ownedActivityEdge.2">
          <returnValue xsi:type="expressions:LiteralExpression" value="null"/>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StoryNode" name="LookupDelegate" comment="LookupDelegate" outgoing="//EdgeProcessor/processEdge/@activity/@ownedActivityEdge.2 //EdgeProcessor/processEdge/@activity/@ownedActivityEdge.3" incoming="//EdgeProcessor/processEdge/@activity/@ownedActivityEdge.4">
          <storyPattern comment="LookupDelegate">
            <objectVariable type="//EdgeProcessor" name="this" outgoingLink="//EdgeProcessor/processEdge/@activity/@ownedActivityNode.4/@storyPattern/@linkVariable.0" bindingState="BOUND"/>
            <objectVariable type="//EdgeProcessor" name="delegate" incomingLink="//EdgeProcessor/processEdge/@activity/@ownedActivityNode.4/@storyPattern/@linkVariable.0"/>
            <linkVariable name="delegate" target="//EdgeProcessor/processEdge/@activity/@ownedActivityNode.4/@storyPattern/@objectVariable.1" source="//EdgeProcessor/processEdge/@activity/@ownedActivityNode.4/@storyPattern/@objectVariable.0" type="//EdgeProcessor/delegate"/>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StartNode" outgoing="//EdgeProcessor/processEdge/@activity/@ownedActivityEdge.4"/>
      </activity>
    </eOperations>
    <eOperations xsi:type="activities:MoflonEOperation" name="processNode">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eParameters name="node" eType="//Node"/>
      <activity owningOperation="//EdgeProcessor/processNode">
        <ownedActivityEdge source="//EdgeProcessor/processNode/@activity/@ownedActivityNode.0" target="//EdgeProcessor/processNode/@activity/@ownedActivityNode.1"/>
        <ownedActivityEdge source="//EdgeProcessor/processNode/@activity/@ownedActivityNode.1" target="//EdgeProcessor/processNode/@activity/@ownedActivityNode.2" guard="FAILURE"/>
        <ownedActivityEdge source="//EdgeProcessor/processNode/@activity/@ownedActivityNode.1" target="//EdgeProcessor/processNode/@activity/@ownedActivityNode.5" guard="SUCCESS"/>
        <ownedActivityEdge source="//EdgeProcessor/processNode/@activity/@ownedActivityNode.5" target="//EdgeProcessor/processNode/@activity/@ownedActivityNode.4" guard="SUCCESS"/>
        <ownedActivityEdge source="//EdgeProcessor/processNode/@activity/@ownedActivityNode.5" target="//EdgeProcessor/processNode/@activity/@ownedActivityNode.3" guard="FAILURE"/>
        <ownedActivityNode xsi:type="activities:StartNode" outgoing="//EdgeProcessor/processNode/@activity/@ownedActivityEdge.0"/>
        <ownedActivityNode xsi:type="activities:StoryNode" name="LookupDelegate" comment="LookupDelegate" outgoing="//EdgeProcessor/processNode/@activity/@ownedActivityEdge.1 //EdgeProcessor/processNode/@activity/@ownedActivityEdge.2" incoming="//EdgeProcessor/processNode/@activity/@ownedActivityEdge.0">
          <storyPattern comment="LookupDelegate">
            <objectVariable type="//EdgeProcessor" name="delegate" incomingLink="//EdgeProcessor/processNode/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.0"/>
            <objectVariable type="//EdgeProcessor" name="this" outgoingLink="//EdgeProcessor/processNode/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.0" bindingState="BOUND"/>
            <linkVariable name="delegate" target="//EdgeProcessor/processNode/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.0" source="//EdgeProcessor/processNode/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.1" type="//EdgeProcessor/delegate"/>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StopNode" incoming="//EdgeProcessor/processNode/@activity/@ownedActivityEdge.1">
          <returnValue xsi:type="expressions:LiteralExpression" value="null"/>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StopNode" incoming="//EdgeProcessor/processNode/@activity/@ownedActivityEdge.4">
          <returnValue xsi:type="expressions:LiteralExpression" value="null"/>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StopNode" incoming="//EdgeProcessor/processNode/@activity/@ownedActivityEdge.3">
          <returnValue xsi:type="patternExpressions:ObjectVariableExpression" object="//EdgeProcessor/processNode/@activity/@ownedActivityNode.5/@storyPattern/@objectVariable.0"/>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StoryNode" name="Delegation" comment="Delegation" outgoing="//EdgeProcessor/processNode/@activity/@ownedActivityEdge.3 //EdgeProcessor/processNode/@activity/@ownedActivityEdge.4" incoming="//EdgeProcessor/processNode/@activity/@ownedActivityEdge.2">
          <storyPattern comment="Delegation">
            <objectVariable name="result" bindingState="BOUND">
              <type xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
              <bindingExpression xsi:type="callExpressions:MethodCallExpression" callee="//EdgeProcessor/processNode">
                <ownedParameterBindings parameter="//EdgeProcessor/processNode/node">
                  <valueExpression xsi:type="callExpressions:ParameterExpression" parameter="//EdgeProcessor/processNode/node"/>
                </ownedParameterBindings>
                <target xsi:type="patternExpressions:ObjectVariableExpression" object="//EdgeProcessor/processNode/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.0"/>
              </bindingExpression>
            </objectVariable>
          </storyPattern>
        </ownedActivityNode>
      </activity>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="delegate" eType="//EdgeProcessor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node">
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" upperBound="-1" eType="//Edge" eOpposite="//Edge/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="graph" lowerBound="1" eType="//DFSGraph" eOpposite="//DFSGraph/nodes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="origin" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" upperBound="-1" eType="//Edge" eOpposite="//Edge/source"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="postTraversal" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="preTraversal" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Edge">
    <eStructuralFeatures xsi:type="ecore:EReference" name="graph" lowerBound="1" eType="//DFSGraph" eOpposite="//DFSGraph/edges"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1" eType="//Node" eOpposite="//Node/outgoing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="origin" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1" eType="//Node" eOpposite="//Node/incoming"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" lowerBound="1" eType="//EdgeType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DepthFirstSearch" eSuperTypes="//EdgeProcessor">
    <eOperations xsi:type="activities:MoflonEOperation" name="incrementPostTraversalCounter">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations xsi:type="activities:MoflonEOperation" name="incrementPreTraversalCounter">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations xsi:type="activities:MoflonEOperation" name="processEdge">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eParameters name="edge" eType="//Edge"/>
      <activity owningOperation="//DepthFirstSearch/processEdge">
        <ownedActivityEdge source="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.0" target="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.7" guard="SUCCESS"/>
        <ownedActivityEdge source="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.0" target="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.5" guard="FAILURE"/>
        <ownedActivityEdge source="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.2" target="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.3"/>
        <ownedActivityEdge source="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.3" target="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.8"/>
        <ownedActivityEdge source="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.4" target="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.7" guard="FAILURE"/>
        <ownedActivityEdge source="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.4" target="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.6" guard="SUCCESS"/>
        <ownedActivityEdge source="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.5" target="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.7"/>
        <ownedActivityEdge source="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.6" target="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.7" guard="FAILURE"/>
        <ownedActivityEdge source="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.6" target="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.1" guard="SUCCESS"/>
        <ownedActivityEdge source="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.8" target="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.10"/>
        <ownedActivityEdge source="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.9" target="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.7" guard="SUCCESS"/>
        <ownedActivityEdge source="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.9" target="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.0" guard="FAILURE"/>
        <ownedActivityEdge source="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.10" target="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.9" guard="FAILURE"/>
        <ownedActivityEdge source="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.10" target="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.4" guard="SUCCESS"/>
        <ownedActivityNode xsi:type="activities:StoryNode" name="SetBackwardEdge" comment="SetBackwardEdge" outgoing="//DepthFirstSearch/processEdge/@activity/@ownedActivityEdge.0 //DepthFirstSearch/processEdge/@activity/@ownedActivityEdge.1" incoming="//DepthFirstSearch/processEdge/@activity/@ownedActivityEdge.11">
          <storyPattern comment="SetBackwardEdge">
            <objectVariable type="//Edge" name="edge" bindingState="BOUND">
              <attributeAssignment attribute="//Edge/type">
                <valueExpression xsi:type="expressions:LiteralExpression" value="DepthFirstSearchGraph.EdgeType.BACKWARD_EDGE"/>
              </attributeAssignment>
            </objectVariable>
            <objectVariable type="//Node" name="targetNode" bindingState="BOUND">
              <constraint>
                <constraintExpression xsi:type="expressions:ComparisonExpression" operator="EQUAL">
                  <rightExpression xsi:type="expressions:LiteralExpression" value="0"/>
                  <leftExpression xsi:type="patternExpressions:AttributeValueExpression" object="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.1" attribute="//Node/postTraversal"/>
                </constraintExpression>
              </constraint>
            </objectVariable>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StopNode" incoming="//DepthFirstSearch/processEdge/@activity/@ownedActivityEdge.8">
          <returnValue xsi:type="patternExpressions:ObjectVariableExpression" object="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.6/@storyPattern/@objectVariable.0"/>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StartNode" outgoing="//DepthFirstSearch/processEdge/@activity/@ownedActivityEdge.2"/>
        <ownedActivityNode xsi:type="activities:StoryNode" name="LookupSourceNode" comment="LookupSourceNode" outgoing="//DepthFirstSearch/processEdge/@activity/@ownedActivityEdge.3" incoming="//DepthFirstSearch/processEdge/@activity/@ownedActivityEdge.2">
          <storyPattern comment="LookupSourceNode">
            <objectVariable type="//Node" name="sourceNode" outgoingLink="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.3/@storyPattern/@linkVariable.0"/>
            <objectVariable type="//Edge" name="edge" incomingLink="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.3/@storyPattern/@linkVariable.0" bindingState="BOUND"/>
            <linkVariable name="outgoing" target="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.3/@storyPattern/@objectVariable.1" source="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.3/@storyPattern/@objectVariable.0" type="//Node/outgoing"/>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StoryNode" name="LookupDelegate" comment="LookupDelegate" outgoing="//DepthFirstSearch/processEdge/@activity/@ownedActivityEdge.4 //DepthFirstSearch/processEdge/@activity/@ownedActivityEdge.5" incoming="//DepthFirstSearch/processEdge/@activity/@ownedActivityEdge.13">
          <storyPattern comment="LookupDelegate">
            <objectVariable type="//EdgeProcessor" name="delegate" incomingLink="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.4/@storyPattern/@linkVariable.0"/>
            <objectVariable type="//DepthFirstSearch" name="this" outgoingLink="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.4/@storyPattern/@linkVariable.0" bindingState="BOUND"/>
            <linkVariable name="delegate" target="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.4/@storyPattern/@objectVariable.0" source="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.4/@storyPattern/@objectVariable.1" type="//EdgeProcessor/delegate"/>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StoryNode" name="SetCrossEdge" comment="SetCrossEdge" outgoing="//DepthFirstSearch/processEdge/@activity/@ownedActivityEdge.6" incoming="//DepthFirstSearch/processEdge/@activity/@ownedActivityEdge.1">
          <storyPattern comment="SetCrossEdge">
            <objectVariable type="//Edge" name="edge" bindingState="BOUND">
              <attributeAssignment attribute="//Edge/type">
                <valueExpression xsi:type="expressions:LiteralExpression" value="DepthFirstSearchGraph.EdgeType.CROSS_EDGE"/>
              </attributeAssignment>
            </objectVariable>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StoryNode" name="ProcessEdge" comment="ProcessEdge" outgoing="//DepthFirstSearch/processEdge/@activity/@ownedActivityEdge.7 //DepthFirstSearch/processEdge/@activity/@ownedActivityEdge.8" incoming="//DepthFirstSearch/processEdge/@activity/@ownedActivityEdge.5">
          <storyPattern comment="ProcessEdge">
            <objectVariable name="result" bindingState="BOUND">
              <type xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
              <bindingExpression xsi:type="callExpressions:MethodCallExpression" callee="//EdgeProcessor/processNode">
                <ownedParameterBindings parameter="//EdgeProcessor/processNode/node">
                  <valueExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.8/@storyPattern/@objectVariable.1"/>
                </ownedParameterBindings>
                <target xsi:type="patternExpressions:ObjectVariableExpression" object="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.4/@storyPattern/@objectVariable.0"/>
              </bindingExpression>
            </objectVariable>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StopNode" incoming="//DepthFirstSearch/processEdge/@activity/@ownedActivityEdge.0 //DepthFirstSearch/processEdge/@activity/@ownedActivityEdge.4 //DepthFirstSearch/processEdge/@activity/@ownedActivityEdge.6 //DepthFirstSearch/processEdge/@activity/@ownedActivityEdge.7 //DepthFirstSearch/processEdge/@activity/@ownedActivityEdge.10">
          <returnValue xsi:type="expressions:LiteralExpression" value="null"/>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StoryNode" name="LookupTargetNode" comment="LookupTargetNode" outgoing="//DepthFirstSearch/processEdge/@activity/@ownedActivityEdge.9" incoming="//DepthFirstSearch/processEdge/@activity/@ownedActivityEdge.3">
          <storyPattern comment="LookupTargetNode">
            <objectVariable type="//Edge" name="edge" incomingLink="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.8/@storyPattern/@linkVariable.0" bindingState="BOUND"/>
            <objectVariable type="//Node" name="targetNode" outgoingLink="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.8/@storyPattern/@linkVariable.0"/>
            <linkVariable name="incoming" target="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.8/@storyPattern/@objectVariable.0" source="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.8/@storyPattern/@objectVariable.1" type="//Node/incoming"/>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StoryNode" name="SetForwardEdge" comment="SetForwardEdge" outgoing="//DepthFirstSearch/processEdge/@activity/@ownedActivityEdge.10 //DepthFirstSearch/processEdge/@activity/@ownedActivityEdge.11" incoming="//DepthFirstSearch/processEdge/@activity/@ownedActivityEdge.12">
          <storyPattern comment="SetForwardEdge">
            <objectVariable type="//Node" name="sourceNode" bindingState="BOUND">
              <constraint>
                <constraintExpression xsi:type="expressions:ComparisonExpression">
                  <rightExpression xsi:type="patternExpressions:AttributeValueExpression" object="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.8/@storyPattern/@objectVariable.1" attribute="//Node/preTraversal"/>
                  <leftExpression xsi:type="patternExpressions:AttributeValueExpression" object="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.9/@storyPattern/@objectVariable.0" attribute="//Node/preTraversal"/>
                </constraintExpression>
              </constraint>
            </objectVariable>
            <objectVariable type="//Edge" name="edge" bindingState="BOUND">
              <attributeAssignment attribute="//Edge/type">
                <valueExpression xsi:type="expressions:LiteralExpression" value="DepthFirstSearchGraph.EdgeType.FORWARD_EDGE"/>
              </attributeAssignment>
            </objectVariable>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StoryNode" name="SetTreeEdge" comment="SetTreeEdge" outgoing="//DepthFirstSearch/processEdge/@activity/@ownedActivityEdge.12 //DepthFirstSearch/processEdge/@activity/@ownedActivityEdge.13" incoming="//DepthFirstSearch/processEdge/@activity/@ownedActivityEdge.9">
          <storyPattern comment="SetTreeEdge">
            <objectVariable type="//Node" name="targetNode" bindingState="BOUND">
              <constraint>
                <constraintExpression xsi:type="expressions:ComparisonExpression" operator="EQUAL">
                  <rightExpression xsi:type="expressions:LiteralExpression" value="0"/>
                  <leftExpression xsi:type="patternExpressions:AttributeValueExpression" object="//DepthFirstSearch/processEdge/@activity/@ownedActivityNode.10/@storyPattern/@objectVariable.0" attribute="//Node/preTraversal"/>
                </constraintExpression>
              </constraint>
            </objectVariable>
            <objectVariable type="//Edge" name="edge" bindingState="BOUND">
              <attributeAssignment attribute="//Edge/type">
                <valueExpression xsi:type="expressions:LiteralExpression" value="DepthFirstSearchGraph.EdgeType.TREE_EDGE"/>
              </attributeAssignment>
            </objectVariable>
          </storyPattern>
        </ownedActivityNode>
      </activity>
    </eOperations>
    <eOperations xsi:type="activities:MoflonEOperation" name="processNode">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eParameters name="node" eType="//Node"/>
      <activity owningOperation="//DepthFirstSearch/processNode">
        <ownedActivityEdge source="//DepthFirstSearch/processNode/@activity/@ownedActivityNode.0" target="//DepthFirstSearch/processNode/@activity/@ownedActivityNode.1"/>
        <ownedActivityEdge source="//DepthFirstSearch/processNode/@activity/@ownedActivityNode.1" target="//DepthFirstSearch/processNode/@activity/@ownedActivityNode.8"/>
        <ownedActivityEdge source="//DepthFirstSearch/processNode/@activity/@ownedActivityNode.2" target="//DepthFirstSearch/processNode/@activity/@ownedActivityNode.0"/>
        <ownedActivityEdge source="//DepthFirstSearch/processNode/@activity/@ownedActivityNode.3" target="//DepthFirstSearch/processNode/@activity/@ownedActivityNode.6"/>
        <ownedActivityEdge source="//DepthFirstSearch/processNode/@activity/@ownedActivityNode.4" target="//DepthFirstSearch/processNode/@activity/@ownedActivityNode.5"/>
        <ownedActivityEdge source="//DepthFirstSearch/processNode/@activity/@ownedActivityNode.6" target="//DepthFirstSearch/processNode/@activity/@ownedActivityNode.9" guard="END"/>
        <ownedActivityEdge source="//DepthFirstSearch/processNode/@activity/@ownedActivityNode.6" target="//DepthFirstSearch/processNode/@activity/@ownedActivityNode.3" guard="EACH_TIME"/>
        <ownedActivityEdge source="//DepthFirstSearch/processNode/@activity/@ownedActivityNode.7" target="//DepthFirstSearch/processNode/@activity/@ownedActivityNode.9" guard="FAILURE"/>
        <ownedActivityEdge source="//DepthFirstSearch/processNode/@activity/@ownedActivityNode.7" target="//DepthFirstSearch/processNode/@activity/@ownedActivityNode.6" guard="SUCCESS"/>
        <ownedActivityEdge source="//DepthFirstSearch/processNode/@activity/@ownedActivityNode.8" target="//DepthFirstSearch/processNode/@activity/@ownedActivityNode.7"/>
        <ownedActivityEdge source="//DepthFirstSearch/processNode/@activity/@ownedActivityNode.9" target="//DepthFirstSearch/processNode/@activity/@ownedActivityNode.4"/>
        <ownedActivityNode xsi:type="activities:StoryNode" name="LookupValidator" comment="LookupValidator" outgoing="//DepthFirstSearch/processNode/@activity/@ownedActivityEdge.0" incoming="//DepthFirstSearch/processNode/@activity/@ownedActivityEdge.2">
          <storyPattern comment="LookupValidator">
            <objectVariable type="//DFSGraph" name="graph" incomingLink="//DepthFirstSearch/processNode/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.0"/>
            <objectVariable type="//Node" name="node" outgoingLink="//DepthFirstSearch/processNode/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.0" bindingState="BOUND"/>
            <linkVariable name="graph" target="//DepthFirstSearch/processNode/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.0" source="//DepthFirstSearch/processNode/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.1" type="//Node/graph"/>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StoryNode" name="IncrementPreTraversalCounter" comment="IncrementPreTraversalCounter" outgoing="//DepthFirstSearch/processNode/@activity/@ownedActivityEdge.1" incoming="//DepthFirstSearch/processNode/@activity/@ownedActivityEdge.0">
          <storyPattern comment="IncrementPreTraversalCounter">
            <objectVariable type="//DepthFirstSearch" name="this" bindingState="BOUND">
              <attributeAssignment attribute="//DepthFirstSearch/preTraversalCounter">
                <valueExpression xsi:type="callExpressions:MethodCallExpression" callee="//DepthFirstSearch/incrementPreTraversalCounter">
                  <target xsi:type="patternExpressions:ObjectVariableExpression" object="//DepthFirstSearch/processNode/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.0"/>
                </valueExpression>
              </attributeAssignment>
            </objectVariable>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StartNode" outgoing="//DepthFirstSearch/processNode/@activity/@ownedActivityEdge.2"/>
        <ownedActivityNode xsi:type="activities:StatementNode" name="ExploreEdge" outgoing="//DepthFirstSearch/processNode/@activity/@ownedActivityEdge.3" incoming="//DepthFirstSearch/processNode/@activity/@ownedActivityEdge.6">
          <statementExpression xsi:type="callExpressions:MethodCallExpression" callee="//EdgeProcessor/processEdge">
            <ownedParameterBindings parameter="//EdgeProcessor/processEdge/edge">
              <valueExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//DepthFirstSearch/processNode/@activity/@ownedActivityNode.6/@storyPattern/@objectVariable.0"/>
            </ownedParameterBindings>
            <target xsi:type="patternExpressions:ObjectVariableExpression" object="//DepthFirstSearch/processNode/@activity/@ownedActivityNode.7/@storyPattern/@objectVariable.1"/>
          </statementExpression>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StoryNode" name="SetPostTraversalCounter" comment="SetPostTraversalCounter" outgoing="//DepthFirstSearch/processNode/@activity/@ownedActivityEdge.4" incoming="//DepthFirstSearch/processNode/@activity/@ownedActivityEdge.10">
          <storyPattern comment="SetPostTraversalCounter">
            <objectVariable type="//Node" name="node" bindingState="BOUND">
              <attributeAssignment attribute="//Node/postTraversal">
                <valueExpression xsi:type="patternExpressions:AttributeValueExpression" object="//DepthFirstSearch/processNode/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.0" attribute="//DepthFirstSearch/postTraversalCounter"/>
              </attributeAssignment>
            </objectVariable>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StopNode" incoming="//DepthFirstSearch/processNode/@activity/@ownedActivityEdge.4">
          <returnValue xsi:type="expressions:LiteralExpression" value="null"/>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StoryNode" name="TraverseOutgoingEdges" comment="TraverseOutgoingEdges" outgoing="//DepthFirstSearch/processNode/@activity/@ownedActivityEdge.5 //DepthFirstSearch/processNode/@activity/@ownedActivityEdge.6" incoming="//DepthFirstSearch/processNode/@activity/@ownedActivityEdge.3 //DepthFirstSearch/processNode/@activity/@ownedActivityEdge.8" forEach="true">
          <storyPattern comment="TraverseOutgoingEdges">
            <objectVariable type="//Edge" name="edge" incomingLink="//DepthFirstSearch/processNode/@activity/@ownedActivityNode.6/@storyPattern/@linkVariable.0"/>
            <objectVariable type="//Node" name="node" outgoingLink="//DepthFirstSearch/processNode/@activity/@ownedActivityNode.6/@storyPattern/@linkVariable.0" bindingState="BOUND"/>
            <linkVariable name="outgoing" target="//DepthFirstSearch/processNode/@activity/@ownedActivityNode.6/@storyPattern/@objectVariable.0" source="//DepthFirstSearch/processNode/@activity/@ownedActivityNode.6/@storyPattern/@objectVariable.1" type="//Node/outgoing"/>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StoryNode" name="LookupDelegate" comment="LookupDelegate" outgoing="//DepthFirstSearch/processNode/@activity/@ownedActivityEdge.7 //DepthFirstSearch/processNode/@activity/@ownedActivityEdge.8" incoming="//DepthFirstSearch/processNode/@activity/@ownedActivityEdge.9">
          <storyPattern comment="LookupDelegate">
            <objectVariable type="//DepthFirstSearch" name="this" outgoingLink="//DepthFirstSearch/processNode/@activity/@ownedActivityNode.7/@storyPattern/@linkVariable.0" bindingState="BOUND"/>
            <objectVariable type="//EdgeProcessor" name="delegate" incomingLink="//DepthFirstSearch/processNode/@activity/@ownedActivityNode.7/@storyPattern/@linkVariable.0"/>
            <linkVariable name="delegate" target="//DepthFirstSearch/processNode/@activity/@ownedActivityNode.7/@storyPattern/@objectVariable.1" source="//DepthFirstSearch/processNode/@activity/@ownedActivityNode.7/@storyPattern/@objectVariable.0" type="//EdgeProcessor/delegate"/>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StoryNode" name="SetPreTraversalCounter" comment="SetPreTraversalCounter" outgoing="//DepthFirstSearch/processNode/@activity/@ownedActivityEdge.9" incoming="//DepthFirstSearch/processNode/@activity/@ownedActivityEdge.1">
          <storyPattern comment="SetPreTraversalCounter">
            <objectVariable type="//Node" name="node" bindingState="BOUND">
              <attributeAssignment attribute="//Node/preTraversal">
                <valueExpression xsi:type="patternExpressions:AttributeValueExpression" object="//DepthFirstSearch/processNode/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.0" attribute="//DepthFirstSearch/preTraversalCounter"/>
              </attributeAssignment>
            </objectVariable>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StoryNode" name="IncrementPostTraversalCounter" comment="IncrementPostTraversalCounter" outgoing="//DepthFirstSearch/processNode/@activity/@ownedActivityEdge.10" incoming="//DepthFirstSearch/processNode/@activity/@ownedActivityEdge.5 //DepthFirstSearch/processNode/@activity/@ownedActivityEdge.7">
          <storyPattern comment="IncrementPostTraversalCounter">
            <objectVariable type="//DepthFirstSearch" name="this" bindingState="BOUND">
              <attributeAssignment attribute="//DepthFirstSearch/postTraversalCounter">
                <valueExpression xsi:type="callExpressions:MethodCallExpression" callee="//DepthFirstSearch/incrementPostTraversalCounter">
                  <target xsi:type="patternExpressions:ObjectVariableExpression" object="//DepthFirstSearch/processNode/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.0"/>
                </valueExpression>
              </attributeAssignment>
            </objectVariable>
          </storyPattern>
        </ownedActivityNode>
      </activity>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="postTraversalCounter" ordered="false" lowerBound="1" defaultValueLiteral="0">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="preTraversalCounter" ordered="false" lowerBound="1" defaultValueLiteral="0">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EdgeType">
    <eLiterals name="TREE_EDGE" value="1" literal="TREE_EDGE"/>
    <eLiterals name="BACKWARD_EDGE" value="2" literal="BACKWARD_EDGE"/>
    <eLiterals name="FORWARD_EDGE" value="3" literal="FORWARD_EDGE"/>
    <eLiterals name="CROSS_EDGE" value="4" literal="CROSS_EDGE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DFSGraph">
    <eStructuralFeatures xsi:type="ecore:EReference" name="edges" upperBound="-1" eType="//Edge" containment="true" eOpposite="//Edge/graph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1" eType="//Node" containment="true" eOpposite="//Node/graph"/>
  </eClassifiers>
</ecore:EPackage>
