/*
 * generated by Xtext 2.12.0
 */
package org.moflon.tie.gt


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ControlflowStandaloneSetup extends ControlflowStandaloneSetupGenerated {

	def static void doSetup() {
		new ControlflowStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
