<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:activities="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//activities" xmlns:callExpressions="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//calls/callExpressions" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:expressions="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//expressions" xmlns:patternExpressions="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//patterns/patternExpressions" name="SDMLanguage" nsURI="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore" nsPrefix="SDMLanguage">
  <eClassifiers xsi:type="ecore:EClass" name="CommentableElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" ordered="false" lowerBound="1" defaultValueLiteral="&quot;&quot;">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1" defaultValueLiteral="&quot;&quot;">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EClassifier"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eSubpackages name="activities" nsURI="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//activities" nsPrefix="activities">
    <eClassifiers xsi:type="ecore:EClass" name="Activity" eSuperTypes="//CommentableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedActivityEdge" upperBound="-1" eType="//activities/ActivityEdge" containment="true" eOpposite="//activities/ActivityEdge/owningActivity"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedActivityNode" upperBound="-1" eType="//activities/ActivityNode" containment="true" eOpposite="//activities/ActivityNode/owningActivity"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="owningOperation">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EOperation"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ActivityEdge">
      <eStructuralFeatures xsi:type="ecore:EReference" name="owningActivity" lowerBound="1" eType="//activities/Activity" eOpposite="//activities/Activity/ownedActivityEdge"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1" eType="//activities/ActivityNode" eOpposite="//activities/ActivityNode/outgoing"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1" eType="//activities/ActivityNode" eOpposite="//activities/ActivityNode/incoming"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="guard" ordered="false" lowerBound="1" eType="//activities/EdgeGuard" defaultValueLiteral="EdgeGuard.NONE"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ActivityNode" abstract="true" eSuperTypes="//NamedElement //CommentableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" upperBound="-1" eType="//activities/ActivityEdge" eOpposite="//activities/ActivityEdge/source"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" upperBound="-1" eType="//activities/ActivityEdge" eOpposite="//activities/ActivityEdge/target"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="owningActivity" lowerBound="1" eType="//activities/Activity" eOpposite="//activities/Activity/ownedActivityNode"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MoflonEOperation">
      <eSuperTypes href="http://www.eclipse.org/emf/2002/Ecore#//EOperation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="activity" eType="//activities/Activity" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StartNode" eSuperTypes="//activities/ActivityNode"/>
    <eClassifiers xsi:type="ecore:EClass" name="StatementNode" eSuperTypes="//activities/ActivityNode">
      <eStructuralFeatures xsi:type="ecore:EReference" name="statementExpression" lowerBound="1" eType="//expressions/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StopNode" eSuperTypes="//activities/ActivityNode">
      <eStructuralFeatures xsi:type="ecore:EReference" name="returnValue" eType="//expressions/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StoryNode" eSuperTypes="//activities/ActivityNode">
      <eStructuralFeatures xsi:type="ecore:EReference" name="storyPattern" lowerBound="1" eType="//patterns/StoryPattern" containment="true" eOpposite="//patterns/StoryPattern/storyNode"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="forEach" ordered="false" lowerBound="1">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="EdgeGuard">
      <eLiterals name="NONE" literal="NONE"/>
      <eLiterals name="SUCCESS" value="1" literal="SUCCESS"/>
      <eLiterals name="FAILURE" value="2" literal="FAILURE"/>
      <eLiterals name="EACH_TIME" value="3" literal="EACH_TIME"/>
      <eLiterals name="END" value="4" literal="END"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="sdmUtil" nsURI="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//sdmUtil" nsPrefix="sdmUtil">
    <eClassifiers xsi:type="ecore:EClass" name="CompilerInjection">
      <eStructuralFeatures xsi:type="ecore:EReference" name="importInjectionEntries" upperBound="-1" eType="//sdmUtil/ImportInjectionEntry" containment="true" eOpposite="//sdmUtil/ImportInjectionEntry/compilerInjection"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="compilerInjectionEntries" upperBound="-1" eType="//sdmUtil/CompilerInjectionEntry" containment="true" eOpposite="//sdmUtil/CompilerInjectionEntry/compilerInjection"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CompilerInjectionEntry">
      <eStructuralFeatures xsi:type="ecore:EReference" name="compilerInjection" lowerBound="1" eType="//sdmUtil/CompilerInjection" eOpposite="//sdmUtil/CompilerInjection/compilerInjectionEntries"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eOperation" lowerBound="1">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EOperation"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" ordered="false" lowerBound="1">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ImportInjectionEntry">
      <eStructuralFeatures xsi:type="ecore:EReference" name="compilerInjection" lowerBound="1" eType="//sdmUtil/CompilerInjection" eOpposite="//sdmUtil/CompilerInjection/importInjectionEntries"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eClass" lowerBound="1">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" ordered="false" lowerBound="1">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SDMPrecompiler">
      <eOperations xsi:type="activities:MoflonEOperation" name="processActivity">
        <eParameters name="activity" eType="//activities/Activity"/>
        <activity owningOperation="//sdmUtil/SDMPrecompiler/processActivity">
          <ownedActivityEdge source="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.0" target="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.1"/>
          <ownedActivityEdge source="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.1" target="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.3" guard="END"/>
          <ownedActivityEdge source="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.1" target="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.2" guard="EACH_TIME"/>
          <ownedActivityEdge source="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.2" target="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.0" guard="FAILURE"/>
          <ownedActivityEdge source="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.2" target="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.1" guard="SUCCESS"/>
          <ownedActivityEdge source="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.4" target="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.1"/>
          <ownedActivityNode xsi:type="activities:StoryNode" name="Create stopnode to handle case when pattern fails" comment="Create_stopnode_to_handle_case_when_pattern_fails" outgoing="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityEdge.0" incoming="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityEdge.3">
            <storyPattern comment="Create_stopnode_to_handle_case_when_pattern_fails">
              <objectVariable type="//activities/Activity" name="activity" incomingLink="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.2 //sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.4" bindingState="BOUND"/>
              <objectVariable type="//expressions/LiteralExpression" name="exceptionExpr" incomingLink="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.3" bindingOperator="CREATE">
                <attributeAssignment attribute="//expressions/LiteralExpression/value">
                  <valueExpression xsi:type="expressions:LiteralExpression" value="&quot;throw new IllegalStateException()&quot;"/>
                </attributeAssignment>
              </objectVariable>
              <objectVariable type="//activities/ActivityEdge" name="failureEdge" incomingLink="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.0 //sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.1" outgoingLink="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.2" bindingOperator="CREATE">
                <attributeAssignment attribute="//activities/ActivityEdge/guard">
                  <valueExpression xsi:type="expressions:LiteralExpression" value="SDMLanguage.activities.EdgeGuard.FAILURE"/>
                </attributeAssignment>
              </objectVariable>
              <objectVariable type="//activities/StopNode" name="newStop" outgoingLink="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.3 //sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.4 //sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.0" bindingOperator="CREATE"/>
              <objectVariable type="//activities/StoryNode" name="storyNode" outgoingLink="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.5 //sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.1" bindingState="BOUND"/>
              <objectVariable type="//activities/ActivityEdge" name="withoutGuard" incomingLink="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.0/@storyPattern/@linkVariable.5" bindingState="BOUND">
                <attributeAssignment attribute="//activities/ActivityEdge/guard">
                  <valueExpression xsi:type="expressions:LiteralExpression" value="SDMLanguage.activities.EdgeGuard.SUCCESS"/>
                </attributeAssignment>
              </objectVariable>
              <linkVariable name="incoming" target="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.2" source="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.3" type="//activities/ActivityNode/incoming" bindingOperator="CREATE"/>
              <linkVariable name="outgoing" target="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.2" source="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.4" type="//activities/ActivityNode/outgoing" bindingOperator="CREATE"/>
              <linkVariable name="owningActivity" target="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.0" source="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.2" type="//activities/ActivityEdge/owningActivity" bindingOperator="CREATE"/>
              <linkVariable name="returnValue" target="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.1" source="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.3" type="//activities/StopNode/returnValue" bindingOperator="CREATE"/>
              <linkVariable name="owningActivity" target="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.0" source="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.3" type="//activities/ActivityNode/owningActivity" bindingOperator="CREATE"/>
              <linkVariable name="outgoing" target="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.5" source="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.0/@storyPattern/@objectVariable.4" type="//activities/ActivityNode/outgoing"/>
            </storyPattern>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StoryNode" name="for all story nodes without success/failure edges" comment="for_all_story_nodes_without_success_failure_edges" outgoing="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityEdge.1 //sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityEdge.2" incoming="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityEdge.0 //sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityEdge.4 //sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityEdge.5" forEach="true">
            <storyPattern comment="for_all_story_nodes_without_success_failure_edges">
              <objectVariable type="//activities/Activity" name="activity" incomingLink="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.0 //sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.1" bindingState="BOUND"/>
              <objectVariable type="//activities/StoryNode" name="storyNode" outgoingLink="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.2 //sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.1"/>
              <objectVariable type="//activities/ActivityEdge" name="withoutGuard" incomingLink="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.2" outgoingLink="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.0">
                <constraint>
                  <constraintExpression xsi:type="expressions:ComparisonExpression" operator="EQUAL">
                    <rightExpression xsi:type="expressions:LiteralExpression" value="SDMLanguage.activities.EdgeGuard.NONE"/>
                    <leftExpression xsi:type="patternExpressions:AttributeValueExpression" object="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.2" attribute="//activities/ActivityEdge/guard"/>
                  </constraintExpression>
                </constraint>
              </objectVariable>
              <linkVariable name="owningActivity" target="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.0" source="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.2" type="//activities/ActivityEdge/owningActivity"/>
              <linkVariable name="owningActivity" target="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.0" source="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.1" type="//activities/ActivityNode/owningActivity"/>
              <linkVariable name="outgoing" target="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.2" source="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.1" type="//activities/ActivityNode/outgoing"/>
            </storyPattern>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StoryNode" name="handle optimization" comment="handle_optimization" outgoing="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityEdge.3 //sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityEdge.4" incoming="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityEdge.2">
            <storyPattern comment="handle_optimization">
              <objectVariable type="//patterns/ObjectVariable" name="other" incomingLink="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.2/@storyPattern/@linkVariable.2" bindingSemantics="NEGATIVE"/>
              <objectVariable type="//activities/StoryNode" name="storyNode" incomingLink="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.2/@storyPattern/@linkVariable.0" bindingState="BOUND"/>
              <objectVariable type="//patterns/StoryPattern" name="storyPattern" outgoingLink="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.2/@storyPattern/@linkVariable.1 //sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.2/@storyPattern/@linkVariable.2 //sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.2/@storyPattern/@linkVariable.0"/>
              <objectVariable type="//patterns/ObjectVariable" name="thisOV" incomingLink="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.2/@storyPattern/@linkVariable.1">
                <constraint>
                  <constraintExpression xsi:type="expressions:ComparisonExpression" operator="EQUAL">
                    <rightExpression xsi:type="expressions:LiteralExpression" value="&quot;this&quot;"/>
                    <leftExpression xsi:type="patternExpressions:AttributeValueExpression" object="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.3" attribute="//NamedElement/name"/>
                  </constraintExpression>
                </constraint>
              </objectVariable>
              <linkVariable name="storyNode" target="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.1" source="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.2" type="//patterns/StoryPattern/storyNode"/>
              <linkVariable name="objectVariable" target="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.3" source="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.2" type="//patterns/StoryPattern/objectVariable"/>
              <linkVariable name="objectVariable" target="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.0" source="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.2" type="//patterns/StoryPattern/objectVariable"/>
            </storyPattern>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StopNode" incoming="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityEdge.1"/>
          <ownedActivityNode xsi:type="activities:StartNode" outgoing="//sdmUtil/SDMPrecompiler/processActivity/@activity/@ownedActivityEdge.5"/>
        </activity>
      </eOperations>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="calls" nsURI="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//calls" nsPrefix="calls">
    <eClassifiers xsi:type="ecore:EClass" name="Invocation" abstract="true" eSuperTypes="//CommentableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedParameterBindings" upperBound="-1" eType="//calls/ParameterBinding" containment="true" eOpposite="//calls/ParameterBinding/invocation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="callee" lowerBound="1">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EOperation"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterBinding" eSuperTypes="//CommentableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="valueExpression" lowerBound="1" eType="//expressions/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="invocation" lowerBound="1" eType="//calls/Invocation" eOpposite="//calls/Invocation/ownedParameterBindings"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EParameter"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eSubpackages name="callExpressions" nsURI="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//calls/callExpressions" nsPrefix="callExpressions">
      <eClassifiers xsi:type="ecore:EClass" name="MethodCallExpression" eSuperTypes="//expressions/Expression //calls/Invocation">
        <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1" eType="//expressions/Expression" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ParameterExpression" eSuperTypes="//expressions/Expression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1">
          <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EParameter"/>
        </eStructuralFeatures>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="expressions" nsURI="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//expressions" nsPrefix="expressions">
    <eClassifiers xsi:type="ecore:EClass" name="BinaryExpression" abstract="true" eSuperTypes="//expressions/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="rightExpression" lowerBound="1" eType="//expressions/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="leftExpression" lowerBound="1" eType="//expressions/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComparisonExpression" eSuperTypes="//expressions/BinaryExpression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" ordered="false" lowerBound="1" eType="//expressions/ComparingOperator"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" eSuperTypes="//CommentableElement">
      <eOperations xsi:type="activities:MoflonEOperation" name="compare">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eParameters name="expression" eType="//expressions/Expression"/>
        <activity owningOperation="//expressions/Expression/compare">
          <ownedActivityEdge source="//expressions/Expression/compare/@activity/@ownedActivityNode.0" target="//expressions/Expression/compare/@activity/@ownedActivityNode.12" guard="FAILURE"/>
          <ownedActivityEdge source="//expressions/Expression/compare/@activity/@ownedActivityNode.0" target="//expressions/Expression/compare/@activity/@ownedActivityNode.20" guard="SUCCESS"/>
          <ownedActivityEdge source="//expressions/Expression/compare/@activity/@ownedActivityNode.1" target="//expressions/Expression/compare/@activity/@ownedActivityNode.8" guard="SUCCESS"/>
          <ownedActivityEdge source="//expressions/Expression/compare/@activity/@ownedActivityNode.1" target="//expressions/Expression/compare/@activity/@ownedActivityNode.10" guard="FAILURE"/>
          <ownedActivityEdge source="//expressions/Expression/compare/@activity/@ownedActivityNode.2" target="//expressions/Expression/compare/@activity/@ownedActivityNode.9" guard="FAILURE"/>
          <ownedActivityEdge source="//expressions/Expression/compare/@activity/@ownedActivityNode.2" target="//expressions/Expression/compare/@activity/@ownedActivityNode.4" guard="SUCCESS"/>
          <ownedActivityEdge source="//expressions/Expression/compare/@activity/@ownedActivityNode.3" target="//expressions/Expression/compare/@activity/@ownedActivityNode.5" guard="SUCCESS"/>
          <ownedActivityEdge source="//expressions/Expression/compare/@activity/@ownedActivityNode.3" target="//expressions/Expression/compare/@activity/@ownedActivityNode.16" guard="FAILURE"/>
          <ownedActivityEdge source="//expressions/Expression/compare/@activity/@ownedActivityNode.4" target="//expressions/Expression/compare/@activity/@ownedActivityNode.3" guard="SUCCESS"/>
          <ownedActivityEdge source="//expressions/Expression/compare/@activity/@ownedActivityNode.4" target="//expressions/Expression/compare/@activity/@ownedActivityNode.23" guard="FAILURE"/>
          <ownedActivityEdge source="//expressions/Expression/compare/@activity/@ownedActivityNode.5" target="//expressions/Expression/compare/@activity/@ownedActivityNode.18" guard="FAILURE"/>
          <ownedActivityEdge source="//expressions/Expression/compare/@activity/@ownedActivityNode.5" target="//expressions/Expression/compare/@activity/@ownedActivityNode.28" guard="SUCCESS"/>
          <ownedActivityEdge source="//expressions/Expression/compare/@activity/@ownedActivityNode.6" target="//expressions/Expression/compare/@activity/@ownedActivityNode.26" guard="SUCCESS"/>
          <ownedActivityEdge source="//expressions/Expression/compare/@activity/@ownedActivityNode.6" target="//expressions/Expression/compare/@activity/@ownedActivityNode.22" guard="FAILURE"/>
          <ownedActivityEdge source="//expressions/Expression/compare/@activity/@ownedActivityNode.7" target="//expressions/Expression/compare/@activity/@ownedActivityNode.27" guard="SUCCESS"/>
          <ownedActivityEdge source="//expressions/Expression/compare/@activity/@ownedActivityNode.7" target="//expressions/Expression/compare/@activity/@ownedActivityNode.24" guard="FAILURE"/>
          <ownedActivityEdge source="//expressions/Expression/compare/@activity/@ownedActivityNode.8" target="//expressions/Expression/compare/@activity/@ownedActivityNode.0"/>
          <ownedActivityEdge source="//expressions/Expression/compare/@activity/@ownedActivityNode.9" target="//expressions/Expression/compare/@activity/@ownedActivityNode.14" guard="FAILURE"/>
          <ownedActivityEdge source="//expressions/Expression/compare/@activity/@ownedActivityNode.9" target="//expressions/Expression/compare/@activity/@ownedActivityNode.7" guard="SUCCESS"/>
          <ownedActivityEdge source="//expressions/Expression/compare/@activity/@ownedActivityNode.10" target="//expressions/Expression/compare/@activity/@ownedActivityNode.21" guard="FAILURE"/>
          <ownedActivityEdge source="//expressions/Expression/compare/@activity/@ownedActivityNode.10" target="//expressions/Expression/compare/@activity/@ownedActivityNode.11" guard="SUCCESS"/>
          <ownedActivityEdge source="//expressions/Expression/compare/@activity/@ownedActivityNode.11" target="//expressions/Expression/compare/@activity/@ownedActivityNode.25" guard="SUCCESS"/>
          <ownedActivityEdge source="//expressions/Expression/compare/@activity/@ownedActivityNode.11" target="//expressions/Expression/compare/@activity/@ownedActivityNode.19" guard="FAILURE"/>
          <ownedActivityEdge source="//expressions/Expression/compare/@activity/@ownedActivityNode.12" target="//expressions/Expression/compare/@activity/@ownedActivityNode.17" guard="FAILURE"/>
          <ownedActivityEdge source="//expressions/Expression/compare/@activity/@ownedActivityNode.12" target="//expressions/Expression/compare/@activity/@ownedActivityNode.29" guard="SUCCESS"/>
          <ownedActivityEdge source="//expressions/Expression/compare/@activity/@ownedActivityNode.13" target="//expressions/Expression/compare/@activity/@ownedActivityNode.2"/>
          <ownedActivityEdge source="//expressions/Expression/compare/@activity/@ownedActivityNode.14" target="//expressions/Expression/compare/@activity/@ownedActivityNode.1" guard="FAILURE"/>
          <ownedActivityEdge source="//expressions/Expression/compare/@activity/@ownedActivityNode.14" target="//expressions/Expression/compare/@activity/@ownedActivityNode.6" guard="SUCCESS"/>
          <ownedActivityEdge source="//expressions/Expression/compare/@activity/@ownedActivityNode.15" target="//expressions/Expression/compare/@activity/@ownedActivityNode.13"/>
          <ownedActivityNode xsi:type="activities:StoryNode" name="attribute equals" comment="attribute_equals" outgoing="//expressions/Expression/compare/@activity/@ownedActivityEdge.0 //expressions/Expression/compare/@activity/@ownedActivityEdge.1" incoming="//expressions/Expression/compare/@activity/@ownedActivityEdge.16">
            <storyPattern comment="attribute_equals">
              <objectVariable name="expAttribute" bindingState="BOUND">
                <type xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
              </objectVariable>
              <objectVariable name="thisAttribute" bindingState="BOUND">
                <type xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
              </objectVariable>
            </storyPattern>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StoryNode" name="attributeValue exp" comment="attributeValue_exp" outgoing="//expressions/Expression/compare/@activity/@ownedActivityEdge.2 //expressions/Expression/compare/@activity/@ownedActivityEdge.3" incoming="//expressions/Expression/compare/@activity/@ownedActivityEdge.26">
            <storyPattern comment="attributeValue_exp">
              <objectVariable type="//patterns/patternExpressions/AttributeValueExpression" name="expressionAttrExp" bindingState="BOUND">
                <bindingExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//expressions/Expression/compare/@activity/@ownedActivityNode.13/@storyPattern/@objectVariable.0"/>
              </objectVariable>
              <objectVariable type="//patterns/patternExpressions/AttributeValueExpression" name="thisAttrExp" outgoingLink="//expressions/Expression/compare/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.0 //expressions/Expression/compare/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.1" bindingState="BOUND">
                <bindingExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//expressions/Expression/compare/@activity/@ownedActivityNode.13/@storyPattern/@objectVariable.1"/>
              </objectVariable>
              <objectVariable name="thisAttribute" incomingLink="//expressions/Expression/compare/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.1">
                <type xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
              </objectVariable>
              <objectVariable type="//patterns/ObjectVariable" name="thisOV" incomingLink="//expressions/Expression/compare/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.0"/>
              <linkVariable name="object" target="//expressions/Expression/compare/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.3" source="//expressions/Expression/compare/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.1" type="//patterns/patternExpressions/ObjectRefExpression/object"/>
              <linkVariable name="attribute" target="//expressions/Expression/compare/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.2" source="//expressions/Expression/compare/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.1" type="//patterns/patternExpressions/AttributeValueExpression/attribute"/>
            </storyPattern>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StoryNode" name="compare exp" comment="compare_exp" outgoing="//expressions/Expression/compare/@activity/@ownedActivityEdge.4 //expressions/Expression/compare/@activity/@ownedActivityEdge.5" incoming="//expressions/Expression/compare/@activity/@ownedActivityEdge.25">
            <storyPattern comment="compare_exp">
              <objectVariable type="//expressions/Expression" name="expLeft" incomingLink="//expressions/Expression/compare/@activity/@ownedActivityNode.2/@storyPattern/@linkVariable.1"/>
              <objectVariable type="//expressions/Expression" name="expRight" incomingLink="//expressions/Expression/compare/@activity/@ownedActivityNode.2/@storyPattern/@linkVariable.0"/>
              <objectVariable type="//expressions/ComparisonExpression" name="expressionComp" outgoingLink="//expressions/Expression/compare/@activity/@ownedActivityNode.2/@storyPattern/@linkVariable.0 //expressions/Expression/compare/@activity/@ownedActivityNode.2/@storyPattern/@linkVariable.1" bindingState="BOUND">
                <bindingExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//expressions/Expression/compare/@activity/@ownedActivityNode.13/@storyPattern/@objectVariable.0"/>
              </objectVariable>
              <objectVariable type="//expressions/ComparisonExpression" name="thisComp" outgoingLink="//expressions/Expression/compare/@activity/@ownedActivityNode.2/@storyPattern/@linkVariable.2 //expressions/Expression/compare/@activity/@ownedActivityNode.2/@storyPattern/@linkVariable.3" bindingState="BOUND">
                <bindingExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//expressions/Expression/compare/@activity/@ownedActivityNode.13/@storyPattern/@objectVariable.1"/>
              </objectVariable>
              <objectVariable type="//expressions/Expression" name="thisLeft" incomingLink="//expressions/Expression/compare/@activity/@ownedActivityNode.2/@storyPattern/@linkVariable.3"/>
              <objectVariable type="//expressions/Expression" name="thisRight" incomingLink="//expressions/Expression/compare/@activity/@ownedActivityNode.2/@storyPattern/@linkVariable.2"/>
              <linkVariable name="rightExpression" target="//expressions/Expression/compare/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.1" source="//expressions/Expression/compare/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.2" type="//expressions/BinaryExpression/rightExpression"/>
              <linkVariable name="leftExpression" target="//expressions/Expression/compare/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.0" source="//expressions/Expression/compare/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.2" type="//expressions/BinaryExpression/leftExpression"/>
              <linkVariable name="rightExpression" target="//expressions/Expression/compare/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.5" source="//expressions/Expression/compare/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.3" type="//expressions/BinaryExpression/rightExpression"/>
              <linkVariable name="leftExpression" target="//expressions/Expression/compare/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.4" source="//expressions/Expression/compare/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.3" type="//expressions/BinaryExpression/leftExpression"/>
            </storyPattern>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StatementNode" name="compare left with left" outgoing="//expressions/Expression/compare/@activity/@ownedActivityEdge.6 //expressions/Expression/compare/@activity/@ownedActivityEdge.7" incoming="//expressions/Expression/compare/@activity/@ownedActivityEdge.8">
            <statementExpression xsi:type="callExpressions:MethodCallExpression" callee="//expressions/Expression/compare">
              <ownedParameterBindings parameter="//expressions/Expression/compare/expression">
                <valueExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//expressions/Expression/compare/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.0"/>
              </ownedParameterBindings>
              <target xsi:type="patternExpressions:ObjectVariableExpression" object="//expressions/Expression/compare/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.4"/>
            </statementExpression>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StoryNode" name="compare operator" comment="compare_operator" outgoing="//expressions/Expression/compare/@activity/@ownedActivityEdge.8 //expressions/Expression/compare/@activity/@ownedActivityEdge.9" incoming="//expressions/Expression/compare/@activity/@ownedActivityEdge.5">
            <storyPattern comment="compare_operator">
              <objectVariable type="//expressions/ComparisonExpression" name="thisComp" bindingState="BOUND">
                <constraint>
                  <constraintExpression xsi:type="expressions:ComparisonExpression" operator="EQUAL">
                    <rightExpression xsi:type="patternExpressions:AttributeValueExpression" object="//expressions/Expression/compare/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.2" attribute="//expressions/ComparisonExpression/operator"/>
                    <leftExpression xsi:type="patternExpressions:AttributeValueExpression" object="//expressions/Expression/compare/@activity/@ownedActivityNode.4/@storyPattern/@objectVariable.0" attribute="//expressions/ComparisonExpression/operator"/>
                  </constraintExpression>
                </constraint>
              </objectVariable>
            </storyPattern>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StatementNode" name="compare right with right" outgoing="//expressions/Expression/compare/@activity/@ownedActivityEdge.10 //expressions/Expression/compare/@activity/@ownedActivityEdge.11" incoming="//expressions/Expression/compare/@activity/@ownedActivityEdge.6">
            <statementExpression xsi:type="callExpressions:MethodCallExpression" callee="//expressions/Expression/compare">
              <ownedParameterBindings parameter="//expressions/Expression/compare/expression">
                <valueExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//expressions/Expression/compare/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.1"/>
              </ownedParameterBindings>
              <target xsi:type="patternExpressions:ObjectVariableExpression" object="//expressions/Expression/compare/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.5"/>
            </statementExpression>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StoryNode" name="compare text" comment="compare_text" outgoing="//expressions/Expression/compare/@activity/@ownedActivityEdge.12 //expressions/Expression/compare/@activity/@ownedActivityEdge.13" incoming="//expressions/Expression/compare/@activity/@ownedActivityEdge.27">
            <storyPattern comment="compare_text">
              <objectVariable type="//expressions/TextualExpression" name="thisText" bindingState="BOUND">
                <constraint>
                  <constraintExpression xsi:type="expressions:ComparisonExpression" operator="EQUAL">
                    <rightExpression xsi:type="patternExpressions:AttributeValueExpression" object="//expressions/Expression/compare/@activity/@ownedActivityNode.14/@storyPattern/@objectVariable.0" attribute="//expressions/TextualExpression/expressionText"/>
                    <leftExpression xsi:type="patternExpressions:AttributeValueExpression" object="//expressions/Expression/compare/@activity/@ownedActivityNode.6/@storyPattern/@objectVariable.0" attribute="//expressions/TextualExpression/expressionText"/>
                  </constraintExpression>
                </constraint>
              </objectVariable>
            </storyPattern>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StoryNode" name="compare value" comment="compare_value" outgoing="//expressions/Expression/compare/@activity/@ownedActivityEdge.14 //expressions/Expression/compare/@activity/@ownedActivityEdge.15" incoming="//expressions/Expression/compare/@activity/@ownedActivityEdge.18">
            <storyPattern comment="compare_value">
              <objectVariable type="//expressions/LiteralExpression" name="thisLit" bindingState="BOUND">
                <constraint>
                  <constraintExpression xsi:type="expressions:ComparisonExpression" operator="EQUAL">
                    <rightExpression xsi:type="patternExpressions:AttributeValueExpression" object="//expressions/Expression/compare/@activity/@ownedActivityNode.9/@storyPattern/@objectVariable.0" attribute="//expressions/LiteralExpression/value"/>
                    <leftExpression xsi:type="patternExpressions:AttributeValueExpression" object="//expressions/Expression/compare/@activity/@ownedActivityNode.7/@storyPattern/@objectVariable.0" attribute="//expressions/LiteralExpression/value"/>
                  </constraintExpression>
                </constraint>
              </objectVariable>
            </storyPattern>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StoryNode" name="get other elements" comment="get_other_elements" outgoing="//expressions/Expression/compare/@activity/@ownedActivityEdge.16" incoming="//expressions/Expression/compare/@activity/@ownedActivityEdge.2">
            <storyPattern comment="get_other_elements">
              <objectVariable name="expAttribute" incomingLink="//expressions/Expression/compare/@activity/@ownedActivityNode.8/@storyPattern/@linkVariable.1">
                <type xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
              </objectVariable>
              <objectVariable type="//patterns/ObjectVariable" name="expOV" incomingLink="//expressions/Expression/compare/@activity/@ownedActivityNode.8/@storyPattern/@linkVariable.0"/>
              <objectVariable type="//patterns/patternExpressions/AttributeValueExpression" name="expressionAttrExp" outgoingLink="//expressions/Expression/compare/@activity/@ownedActivityNode.8/@storyPattern/@linkVariable.0 //expressions/Expression/compare/@activity/@ownedActivityNode.8/@storyPattern/@linkVariable.1" bindingState="BOUND"/>
              <linkVariable name="object" target="//expressions/Expression/compare/@activity/@ownedActivityNode.8/@storyPattern/@objectVariable.1" source="//expressions/Expression/compare/@activity/@ownedActivityNode.8/@storyPattern/@objectVariable.2" type="//patterns/patternExpressions/ObjectRefExpression/object"/>
              <linkVariable name="attribute" target="//expressions/Expression/compare/@activity/@ownedActivityNode.8/@storyPattern/@objectVariable.0" source="//expressions/Expression/compare/@activity/@ownedActivityNode.8/@storyPattern/@objectVariable.2" type="//patterns/patternExpressions/AttributeValueExpression/attribute"/>
            </storyPattern>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StoryNode" name="literal exp" comment="literal_exp" outgoing="//expressions/Expression/compare/@activity/@ownedActivityEdge.17 //expressions/Expression/compare/@activity/@ownedActivityEdge.18" incoming="//expressions/Expression/compare/@activity/@ownedActivityEdge.4">
            <storyPattern comment="literal_exp">
              <objectVariable type="//expressions/LiteralExpression" name="expressionLit" bindingState="BOUND">
                <bindingExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//expressions/Expression/compare/@activity/@ownedActivityNode.13/@storyPattern/@objectVariable.0"/>
              </objectVariable>
              <objectVariable type="//expressions/LiteralExpression" name="thisLit" bindingState="BOUND">
                <bindingExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//expressions/Expression/compare/@activity/@ownedActivityNode.13/@storyPattern/@objectVariable.1"/>
              </objectVariable>
            </storyPattern>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StoryNode" name="objectValue exp" comment="objectValue_exp" outgoing="//expressions/Expression/compare/@activity/@ownedActivityEdge.19 //expressions/Expression/compare/@activity/@ownedActivityEdge.20" incoming="//expressions/Expression/compare/@activity/@ownedActivityEdge.3">
            <storyPattern comment="objectValue_exp">
              <objectVariable type="//patterns/patternExpressions/ObjectVariableExpression" name="expressionOVExp" bindingState="BOUND">
                <bindingExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//expressions/Expression/compare/@activity/@ownedActivityNode.13/@storyPattern/@objectVariable.0"/>
              </objectVariable>
              <objectVariable type="//patterns/patternExpressions/ObjectVariableExpression" name="thisOVExp" bindingState="BOUND">
                <bindingExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//expressions/Expression/compare/@activity/@ownedActivityNode.13/@storyPattern/@objectVariable.1"/>
              </objectVariable>
            </storyPattern>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StoryNode" name="ov equals" comment="ov_equals" outgoing="//expressions/Expression/compare/@activity/@ownedActivityEdge.21 //expressions/Expression/compare/@activity/@ownedActivityEdge.22" incoming="//expressions/Expression/compare/@activity/@ownedActivityEdge.20">
            <storyPattern comment="ov_equals">
              <objectVariable type="//patterns/ObjectVariable" name="expOV" incomingLink="//expressions/Expression/compare/@activity/@ownedActivityNode.11/@storyPattern/@linkVariable.0 //expressions/Expression/compare/@activity/@ownedActivityNode.11/@storyPattern/@linkVariable.1"/>
              <objectVariable type="//patterns/patternExpressions/ObjectVariableExpression" name="expressionOVExp" outgoingLink="//expressions/Expression/compare/@activity/@ownedActivityNode.11/@storyPattern/@linkVariable.0" bindingState="BOUND"/>
              <objectVariable type="//patterns/patternExpressions/ObjectVariableExpression" name="thisOVExp" outgoingLink="//expressions/Expression/compare/@activity/@ownedActivityNode.11/@storyPattern/@linkVariable.1" bindingState="BOUND"/>
              <linkVariable name="object" target="//expressions/Expression/compare/@activity/@ownedActivityNode.11/@storyPattern/@objectVariable.0" source="//expressions/Expression/compare/@activity/@ownedActivityNode.11/@storyPattern/@objectVariable.1" type="//patterns/patternExpressions/ObjectRefExpression/object"/>
              <linkVariable name="object" target="//expressions/Expression/compare/@activity/@ownedActivityNode.11/@storyPattern/@objectVariable.0" source="//expressions/Expression/compare/@activity/@ownedActivityNode.11/@storyPattern/@objectVariable.2" type="//patterns/patternExpressions/ObjectRefExpression/object"/>
            </storyPattern>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StoryNode" name="ov the same?" comment="ov_the_same_" outgoing="//expressions/Expression/compare/@activity/@ownedActivityEdge.23 //expressions/Expression/compare/@activity/@ownedActivityEdge.24" incoming="//expressions/Expression/compare/@activity/@ownedActivityEdge.0">
            <storyPattern comment="ov_the_same_">
              <objectVariable type="//patterns/ObjectVariable" name="expOV" incomingLink="//expressions/Expression/compare/@activity/@ownedActivityNode.12/@storyPattern/@linkVariable.0" bindingState="BOUND"/>
              <objectVariable type="//patterns/patternExpressions/AttributeValueExpression" name="thisAttrExp" outgoingLink="//expressions/Expression/compare/@activity/@ownedActivityNode.12/@storyPattern/@linkVariable.0" bindingState="BOUND"/>
              <linkVariable name="object" target="//expressions/Expression/compare/@activity/@ownedActivityNode.12/@storyPattern/@objectVariable.0" source="//expressions/Expression/compare/@activity/@ownedActivityNode.12/@storyPattern/@objectVariable.1" type="//patterns/patternExpressions/ObjectRefExpression/object"/>
            </storyPattern>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StoryNode" name="prepare" comment="prepare" outgoing="//expressions/Expression/compare/@activity/@ownedActivityEdge.25" incoming="//expressions/Expression/compare/@activity/@ownedActivityEdge.28">
            <storyPattern comment="prepare">
              <objectVariable type="//expressions/Expression" name="expression" bindingState="BOUND"/>
              <objectVariable type="//expressions/Expression" name="this" bindingState="BOUND"/>
            </storyPattern>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StoryNode" name="textual exp" comment="textual_exp" outgoing="//expressions/Expression/compare/@activity/@ownedActivityEdge.26 //expressions/Expression/compare/@activity/@ownedActivityEdge.27" incoming="//expressions/Expression/compare/@activity/@ownedActivityEdge.17">
            <storyPattern comment="textual_exp">
              <objectVariable type="//expressions/TextualExpression" name="expressionText" bindingState="BOUND">
                <bindingExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//expressions/Expression/compare/@activity/@ownedActivityNode.13/@storyPattern/@objectVariable.0"/>
              </objectVariable>
              <objectVariable type="//expressions/TextualExpression" name="thisText" bindingState="BOUND">
                <bindingExpression xsi:type="patternExpressions:ObjectVariableExpression" object="//expressions/Expression/compare/@activity/@ownedActivityNode.13/@storyPattern/@objectVariable.1"/>
              </objectVariable>
            </storyPattern>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StartNode" outgoing="//expressions/Expression/compare/@activity/@ownedActivityEdge.28"/>
          <ownedActivityNode xsi:type="activities:StopNode" incoming="//expressions/Expression/compare/@activity/@ownedActivityEdge.7">
            <returnValue xsi:type="expressions:LiteralExpression" value="false"/>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StopNode" incoming="//expressions/Expression/compare/@activity/@ownedActivityEdge.23">
            <returnValue xsi:type="expressions:LiteralExpression" value="false"/>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StopNode" incoming="//expressions/Expression/compare/@activity/@ownedActivityEdge.10">
            <returnValue xsi:type="expressions:LiteralExpression" value="false"/>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StopNode" incoming="//expressions/Expression/compare/@activity/@ownedActivityEdge.22">
            <returnValue xsi:type="expressions:LiteralExpression" value="false"/>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StopNode" incoming="//expressions/Expression/compare/@activity/@ownedActivityEdge.1">
            <returnValue xsi:type="expressions:LiteralExpression" value="false"/>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StopNode" incoming="//expressions/Expression/compare/@activity/@ownedActivityEdge.19">
            <returnValue xsi:type="expressions:LiteralExpression" value="false"/>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StopNode" incoming="//expressions/Expression/compare/@activity/@ownedActivityEdge.13">
            <returnValue xsi:type="expressions:LiteralExpression" value="false"/>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StopNode" incoming="//expressions/Expression/compare/@activity/@ownedActivityEdge.9">
            <returnValue xsi:type="expressions:LiteralExpression" value="false"/>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StopNode" incoming="//expressions/Expression/compare/@activity/@ownedActivityEdge.15">
            <returnValue xsi:type="expressions:LiteralExpression" value="false"/>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StopNode" incoming="//expressions/Expression/compare/@activity/@ownedActivityEdge.21">
            <returnValue xsi:type="expressions:LiteralExpression" value="true"/>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StopNode" incoming="//expressions/Expression/compare/@activity/@ownedActivityEdge.12">
            <returnValue xsi:type="expressions:LiteralExpression" value="true"/>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StopNode" incoming="//expressions/Expression/compare/@activity/@ownedActivityEdge.14">
            <returnValue xsi:type="expressions:LiteralExpression" value="true"/>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StopNode" incoming="//expressions/Expression/compare/@activity/@ownedActivityEdge.11">
            <returnValue xsi:type="expressions:LiteralExpression" value="true"/>
          </ownedActivityNode>
          <ownedActivityNode xsi:type="activities:StopNode" incoming="//expressions/Expression/compare/@activity/@ownedActivityEdge.24">
            <returnValue xsi:type="expressions:LiteralExpression" value="true"/>
          </ownedActivityNode>
        </activity>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LiteralExpression" eSuperTypes="//expressions/Expression //TypedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" lowerBound="1">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TextualExpression" eSuperTypes="//expressions/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="expressionText" ordered="false" lowerBound="1">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" ordered="false" lowerBound="1">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="languageVersion" ordered="false" lowerBound="1">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ComparingOperator">
      <eLiterals name="LESS" literal="LESS"/>
      <eLiterals name="LESS_OR_EQUAL" value="1" literal="LESS_OR_EQUAL"/>
      <eLiterals name="EQUAL" value="2" literal="EQUAL"/>
      <eLiterals name="GREATER_OR_EQUAL" value="3" literal="GREATER_OR_EQUAL"/>
      <eLiterals name="GREATER" value="4" literal="GREATER"/>
      <eLiterals name="UNEQUAL" value="5" literal="UNEQUAL"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="patterns" nsURI="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//patterns" nsPrefix="patterns">
    <eClassifiers xsi:type="ecore:EClass" name="ApplicationConditionStoryPattern" eSuperTypes="//patterns/StoryPattern">
      <eStructuralFeatures xsi:type="ecore:EReference" name="storyPattern" lowerBound="1" eType="//patterns/StoryPattern" eOpposite="//patterns/StoryPattern/applicationConditions"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AttributeAssignment">
      <eStructuralFeatures xsi:type="ecore:EReference" name="objectVariable" lowerBound="1" eType="//patterns/ObjectVariable" eOpposite="//patterns/ObjectVariable/attributeAssignment"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="valueExpression" lowerBound="1" eType="//expressions/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" lowerBound="1">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Constraint">
      <eStructuralFeatures xsi:type="ecore:EReference" name="constraintExpression" lowerBound="1" eType="//expressions/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="objectVariable" lowerBound="1" eType="//patterns/ObjectVariable" eOpposite="//patterns/ObjectVariable/constraint"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LinkVariable" eSuperTypes="//NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1" eType="//patterns/ObjectVariable" eOpposite="//patterns/ObjectVariable/incomingLink"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1" eType="//patterns/ObjectVariable" eOpposite="//patterns/ObjectVariable/outgoingLink"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" lowerBound="1" eType="//patterns/StoryPattern" eOpposite="//patterns/StoryPattern/linkVariable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bindingOperator" ordered="false" lowerBound="1" eType="//patterns/BindingOperator"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bindingSemantics" ordered="false" lowerBound="1" eType="//patterns/BindingSemantics"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ObjectVariable" eSuperTypes="//TypedElement //NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="constraint" upperBound="-1" eType="//patterns/Constraint" containment="true" eOpposite="//patterns/Constraint/objectVariable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="bindingExpression" eType="//expressions/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" lowerBound="1" eType="//patterns/StoryPattern" eOpposite="//patterns/StoryPattern/objectVariable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="incomingLink" upperBound="-1" eType="//patterns/LinkVariable" eOpposite="//patterns/LinkVariable/target"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingLink" upperBound="-1" eType="//patterns/LinkVariable" eOpposite="//patterns/LinkVariable/source"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attributeAssignment" upperBound="-1" eType="//patterns/AttributeAssignment" containment="true" eOpposite="//patterns/AttributeAssignment/objectVariable"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bindingOperator" ordered="false" lowerBound="1" eType="//patterns/BindingOperator"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bindingSemantics" ordered="false" lowerBound="1" eType="//patterns/BindingSemantics"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bindingState" ordered="false" lowerBound="1" eType="//patterns/BindingState"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StoryPattern" eSuperTypes="//CommentableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="objectVariable" upperBound="-1" eType="//patterns/ObjectVariable" containment="true" eOpposite="//patterns/ObjectVariable/pattern"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="linkVariable" upperBound="-1" eType="//patterns/LinkVariable" containment="true" eOpposite="//patterns/LinkVariable/pattern"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1" eType="//patterns/AttributeConstraints/AttributeConstraint" containment="true" eOpposite="//patterns/AttributeConstraints/AttributeConstraint/storyPattern"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1" eType="//patterns/AttributeConstraints/AttributeConstraintVariable" containment="true" eOpposite="//patterns/AttributeConstraints/AttributeConstraintVariable/storyPattern"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="applicationConditions" upperBound="-1" eType="//patterns/ApplicationConditionStoryPattern" containment="true" eOpposite="//patterns/ApplicationConditionStoryPattern/storyPattern"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="storyNode" lowerBound="1" eType="//activities/StoryNode" eOpposite="//activities/StoryNode/storyPattern"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="BindingOperator">
      <eLiterals name="CHECK_ONLY" literal="CHECK_ONLY"/>
      <eLiterals name="CREATE" value="1" literal="CREATE"/>
      <eLiterals name="DESTROY" value="2" literal="DESTROY"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="BindingSemantics">
      <eLiterals name="MANDATORY" literal="MANDATORY"/>
      <eLiterals name="OPTIONAL" value="2" literal="OPTIONAL"/>
      <eLiterals name="NEGATIVE" value="1" literal="NEGATIVE"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="BindingState">
      <eLiterals name="UNBOUND" literal="UNBOUND"/>
      <eLiterals name="BOUND" value="1" literal="BOUND"/>
    </eClassifiers>
    <eSubpackages name="AttributeConstraints" nsURI="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//patterns/AttributeConstraints" nsPrefix="AttributeConstraints">
      <eClassifiers xsi:type="ecore:EClass" name="AssignmentConstraint" eSuperTypes="//patterns/AttributeConstraints/AttributeValueConstraint"/>
      <eClassifiers xsi:type="ecore:EClass" name="AttributeConstraint">
        <eStructuralFeatures xsi:type="ecore:EReference" name="storyPattern" lowerBound="1" eType="//patterns/StoryPattern" eOpposite="//patterns/StoryPattern/constraints"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="AttributeConstraintExpression" eSuperTypes="//expressions/Expression">
        <eOperations xsi:type="activities:MoflonEOperation" name="compare">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
          <eParameters name="expression" eType="//expressions/Expression"/>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="targetVariable" lowerBound="1" eType="//patterns/AttributeConstraints/AttributeConstraintVariable"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="containedVariables" upperBound="-1" eType="//patterns/AttributeConstraints/AttributeConstraintVariable" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="containedConstraints" upperBound="-1" eType="//patterns/AttributeConstraints/AttributeConstraint" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="AttributeConstraintVariable">
        <eStructuralFeatures xsi:type="ecore:EReference" name="storyPattern" eType="//patterns/StoryPattern" eOpposite="//patterns/StoryPattern/variables"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="attributeValueConstraints" upperBound="-1" eType="//patterns/AttributeConstraints/AttributeValueConstraint" eOpposite="//patterns/AttributeConstraints/AttributeValueConstraint/parameter"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="type">
          <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EDataType"/>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="AttributeLookupConstraint" eSuperTypes="//patterns/AttributeConstraints/AttributeValueConstraint"/>
      <eClassifiers xsi:type="ecore:EClass" name="AttributeValueConstraint" eSuperTypes="//patterns/AttributeConstraints/AttributeConstraint">
        <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" eType="//patterns/AttributeConstraints/AttributeConstraintVariable" eOpposite="//patterns/AttributeConstraints/AttributeConstraintVariable/attributeValueConstraints"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="objectVariable" eType="//patterns/ObjectVariable"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="type">
          <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="CspConstraint" eSuperTypes="//patterns/AttributeConstraints/AttributeConstraint">
        <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1" eType="//patterns/AttributeConstraints/CspConstraintVariableReference" containment="true" eOpposite="//patterns/AttributeConstraints/CspConstraintVariableReference/cspConstraint"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="LiteralVariable" eSuperTypes="//patterns/AttributeConstraints/AttributeConstraintVariable"/>
      <eClassifiers xsi:type="ecore:EClass" name="PrimitiveVariable" eSuperTypes="//patterns/AttributeConstraints/AttributeConstraintVariable"/>
      <eClassifiers xsi:type="ecore:EClass" name="CspConstraintVariableReference">
        <eStructuralFeatures xsi:type="ecore:EReference" name="cspConstraint" eType="//patterns/AttributeConstraints/CspConstraint" eOpposite="//patterns/AttributeConstraints/CspConstraint/parameters"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="attributeConstraintVariable" eType="//patterns/AttributeConstraints/AttributeConstraintVariable"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="patternExpressions" nsURI="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//patterns/patternExpressions" nsPrefix="patternExpressions">
      <eClassifiers xsi:type="ecore:EClass" name="AttributeValueExpression" eSuperTypes="//patterns/patternExpressions/ObjectRefExpression //expressions/Expression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" lowerBound="1">
          <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ObjectRefExpression" abstract="true" eSuperTypes="//expressions/Expression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="object" lowerBound="1" eType="//patterns/ObjectVariable"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ObjectVariableExpression" eSuperTypes="//expressions/Expression //patterns/patternExpressions/ObjectRefExpression"/>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
