/*
 * generated by Xtext 2.11.0
 */
package org.moflon.tie.gt.mosl.controlflow.language.ide
import org.moflon.tie.gt.mosl.controlflow.language.ide.AbstractMOSLControlFlowIdeModule

/**
 * Use this class to register ide components.
 */
class MOSLControlFlowIdeModule extends AbstractMOSLControlFlowIdeModule {
}
